# Generated by Django 5.1.15 on 2026-07-11 12:19

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0007_customer_b2b_order_projects_enabled'),
        ('orders', '0003_order_meterage_override_linear_m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BOrderProjectNumberSequence',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('next_value', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Séquence de numéro de projet B2B',
            },
        ),
        migrations.CreateModel(
            name='B2BOrderProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('project_number', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('customer_reference', models.CharField(blank=True, max_length=128)),
                ('end_customer_reference', models.CharField(blank=True, max_length=128)),
                ('order_mode', models.CharField(choices=[('individual_designs', 'Visuels individuels'), ('ready_gang_sheet', 'Planche prête à imprimer'), ('reorder', 'Recommande')], default='individual_designs', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('incomplete', 'Incomplet'), ('analyzing', 'Analyse en cours'), ('action_required', 'Action requise'), ('ready_to_submit', 'Prêt à transmettre'), ('submitted', 'Transmis'), ('under_review', 'En contrôle'), ('changes_requested', 'Corrections demandées'), ('price_confirmation_required', 'Tarif à confirmer'), ('confirmed', 'Confirmé'), ('converted', 'Converti'), ('cancelled', 'Annulé'), ('blocked', 'Bloqué')], default='draft', max_length=40)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=32)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('customer_comment', models.TextField(blank=True)),
                ('internal_comment', models.TextField(blank=True)),
                ('estimated_length_mm', models.PositiveBigIntegerField(blank=True, null=True)),
                ('confirmed_length_mm', models.PositiveBigIntegerField(blank=True, null=True)),
                ('estimated_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estimated_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estimated_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('confirmed_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('confirmed_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('confirmed_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_confirmation_required', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('review_started_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_b2b_order_project', to='orders.order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_b2b_order_projects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_order_projects', to='customers.customer')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'permissions': [('review_b2borderproject', 'Can review B2B order projects'), ('force_transition_b2borderproject', 'Can force B2B order project transitions')],
            },
        ),
        migrations.CreateModel(
            name='B2BOrderProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('customer_reference', models.CharField(blank=True, max_length=128)),
                ('placement', models.CharField(blank=True, max_length=128)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rotation_allowed', models.BooleanField(default=True)),
                ('individual_cutting', models.BooleanField(default=False)),
                ('customer_comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'À compléter'), ('ready', 'Prêt'), ('action_required', 'Action requise')], default='ready', max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_order_project_items', to='customers.customer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='b2b_order_projects.b2borderproject')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='b2borderproject',
            index=models.Index(fields=['customer', 'status', 'created_at'], name='b2b_order_p_custome_0e257f_idx'),
        ),
        migrations.AddIndex(
            model_name='b2borderproject',
            index=models.Index(fields=['customer', 'updated_at'], name='b2b_order_p_custome_3cc0a9_idx'),
        ),
        migrations.AddIndex(
            model_name='b2borderproject',
            index=models.Index(fields=['status', 'submitted_at'], name='b2b_order_p_status_272b26_idx'),
        ),
        migrations.AddIndex(
            model_name='b2borderprojectitem',
            index=models.Index(fields=['customer', 'project', 'sort_order'], name='b2b_order_p_custome_fb129b_idx'),
        ),
        migrations.AddIndex(
            model_name='b2borderprojectitem',
            index=models.Index(fields=['customer', 'status'], name='b2b_order_p_custome_29ee72_idx'),
        ),
        migrations.AddConstraint(
            model_name='b2borderprojectitem',
            constraint=models.CheckConstraint(condition=models.Q(('width_mm__gt', 0)), name='b2b_item_width_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='b2borderprojectitem',
            constraint=models.CheckConstraint(condition=models.Q(('height_mm__gt', 0)), name='b2b_item_height_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='b2borderprojectitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='b2b_item_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='b2borderprojectitem',
            constraint=models.UniqueConstraint(fields=('customer', 'project', 'sort_order'), name='uniq_b2b_project_item_position'),
        ),
    ]
