# Generated by Django 5.1.15 on 2026-07-11 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_order_projects', '0001_initial'),
        ('uploads', '0011_backfill_order_upload_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2borderprojectitem',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='b2b_order_project_items', to='uploads.asset'),
        ),
    ]
