# Generated by Django 5.2.17 on 2026-08-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_order_projects', '0009_project_number_prefix_by_order_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='b2borderprojectnumbersequence',
            options={'verbose_name': 'Séquence de numéro de projet B2B'},
        ),
    ]
