# Generated by Django 5.2.17 on 2026-08-30 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0018_volumediscountdashboardcopy'),
        ('pod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('code',),
                'permissions': [('manage_warehouse', 'Can manage warehouse zones and locations')],
            },
        ),
        migrations.CreateModel(
            name='WarehouseZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('blanks', 'Vierges POD'), ('finished', 'Produits finis'), ('returns', 'Retours'), ('production', 'Staging production'), ('client', 'Stock client')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='inventory.warehouse')),
            ],
            options={
                'ordering': ('warehouse_id', 'code'),
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='inventory.warehousezone')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sku_kind', models.CharField(choices=[('blank', 'Blank vierge'), ('finished', 'Produit fini'), ('return', 'Retour restockable')], max_length=16)),
                ('finished_sku', models.CharField(blank=True, default='', max_length=80)),
                ('owner_kind', models.CharField(choices=[('atelier', 'Atelier'), ('customer', 'Client')], default='atelier', max_length=16)),
                ('qty_on_hand', models.PositiveIntegerField(default=0)),
                ('qty_reserved', models.PositiveIntegerField(default=0)),
                ('blank_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='pod.blankvariant')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='customers.customer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='inventory.storagelocation')),
            ],
            options={
                'ordering': ('location__code',),
                'indexes': [models.Index(fields=['sku_kind', 'owner_kind', 'location'], name='inventory_s_sku_kin_3282ed_idx')],
                'constraints': [models.UniqueConstraint(fields=('sku_kind', 'blank_variant', 'finished_sku', 'location', 'owner_kind', 'customer'), name='inventory_stock_balance_uniq', nulls_distinct=False), models.CheckConstraint(condition=models.Q(('qty_reserved__lte', models.F('qty_on_hand'))), name='inventory_stock_reserved_lte_on_hand')],
            },
        ),
        migrations.CreateModel(
            name='ProductLocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sku_kind', models.CharField(choices=[('blank', 'Blank vierge'), ('finished', 'Produit fini'), ('return', 'Retour restockable')], max_length=16)),
                ('finished_sku', models.CharField(blank=True, default='', max_length=80)),
                ('owner_kind', models.CharField(choices=[('atelier', 'Atelier'), ('customer', 'Client')], default='atelier', max_length=16)),
                ('blank_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_rules', to='pod.blankvariant')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_location_rules', to='customers.customer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_rules', to='inventory.storagelocation')),
            ],
            options={
                'ordering': ('sku_kind', 'finished_sku'),
                'indexes': [models.Index(fields=['sku_kind', 'owner_kind'], name='inventory_p_sku_kin_a0c44c_idx')],
                'constraints': [models.UniqueConstraint(fields=('sku_kind', 'blank_variant', 'finished_sku', 'owner_kind', 'customer'), name='inventory_product_location_rule_uniq', nulls_distinct=False)],
            },
        ),
        migrations.AddIndex(
            model_name='warehousezone',
            index=models.Index(fields=['warehouse', 'kind', 'is_active'], name='inventory_w_warehou_49edd2_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehousezone',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='inventory_warehouse_zone_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['zone', 'is_active'], name='inventory_s_zone_id_9a2847_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['is_active', 'code'], name='inventory_s_is_acti_fb3020_idx'),
        ),
    ]
