# Generated by Django 5.2.17 on 2026-08-30 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('pod', '0004_pod_units_webhook_stock_movements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('receipt', 'Réception'), ('pick', 'Picking'), ('putaway', 'Rangement'), ('transfer', 'Transfert'), ('adjustment', 'Ajustement')], max_length=16)),
                ('sku_kind', models.CharField(choices=[('blank', 'Blank vierge'), ('finished', 'Produit fini'), ('return', 'Retour restockable')], max_length=16)),
                ('finished_sku', models.CharField(blank=True, default='', max_length=80)),
                ('owner_kind', models.CharField(choices=[('atelier', 'Atelier'), ('customer', 'Client')], default='atelier', max_length=16)),
                ('quantity', models.PositiveIntegerField()),
                ('scanned_bin_code', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('blank_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='pod.blankvariant')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_movements', to='inventory.storagelocation')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_movements', to='inventory.storagelocation')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['kind', 'created_at'], name='inventory_s_kind_25c142_idx')],
            },
        ),
    ]
