# Generated by Django 5.1.15 on 2026-04-02 04:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_production_jobs(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    ProductionJob = apps.get_model("production", "ProductionJob")

    existing_order_ids = set(
        ProductionJob.objects.values_list("order_id", flat=True)
    )
    jobs_to_create = []
    for order in Order.objects.exclude(pk__in=existing_order_ids).iterator():
        jobs_to_create.append(
            ProductionJob(
                order_id=order.pk,
                manufacturing_order_number=(
                    f"OF-{order.created_at:%Y%m%d}-{str(order.public_id).split('-')[0].upper()}"
                ),
                status="queued",
            )
        )

    if jobs_to_create:
        ProductionJob.objects.bulk_create(jobs_to_create)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('manufacturing_order_number', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In progress'), ('ready_to_ship', 'Ready to ship'), ('blocked', 'Blocked'), ('completed', 'Completed')], default='queued', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_transition_at', models.DateTimeField(blank=True, null=True)),
                ('last_transition_note', models.CharField(blank=True, max_length=255)),
                ('last_transition_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_jobs_last_changed', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_job', to='orders.order')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'permissions': [('transition_productionjob', 'Can transition production job')],
            },
        ),
        migrations.CreateModel(
            name='ProductionJobTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('from_status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In progress'), ('ready_to_ship', 'Ready to ship'), ('blocked', 'Blocked'), ('completed', 'Completed')], max_length=32)),
                ('to_status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In progress'), ('ready_to_ship', 'Ready to ship'), ('blocked', 'Blocked'), ('completed', 'Completed')], max_length=32)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(default='staff_api', max_length=32)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_job_transitions', to=settings.AUTH_USER_MODEL)),
                ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='production.productionjob')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='productionjob',
            index=models.Index(fields=['status', 'updated_at'], name='production__status_d19081_idx'),
        ),
        migrations.AddIndex(
            model_name='productionjob',
            index=models.Index(fields=['manufacturing_order_number'], name='production__manufac_f4c843_idx'),
        ),
        migrations.AddIndex(
            model_name='productionjobtransition',
            index=models.Index(fields=['production_job', 'created_at'], name='production__product_45514b_idx'),
        ),
        migrations.AddIndex(
            model_name='productionjobtransition',
            index=models.Index(fields=['to_status', 'created_at'], name='production__to_stat_050f04_idx'),
        ),
        migrations.RunPython(backfill_production_jobs, migrations.RunPython.noop),
    ]
