# Generated by Django 5.1.15 on 2026-04-02 05:14

import apps.production.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_scan_identifiers(apps, schema_editor):
    ProductionJob = apps.get_model("production", "ProductionJob")

    known_identifiers = set(
        ProductionJob.objects.exclude(scan_identifier__isnull=True).values_list(
            "scan_identifier", flat=True
        )
    )

    for production_job in ProductionJob.objects.filter(scan_identifier__isnull=True).iterator():
        production_job.scan_identifier = ""
        while not production_job.scan_identifier or production_job.scan_identifier in known_identifiers:
            production_job.scan_identifier = f"PJSCAN-{uuid.uuid4().hex[:20].upper()}"
        known_identifiers.add(production_job.scan_identifier)
        production_job.save(update_fields=["scan_identifier"])


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionJobScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('scan_identifier', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('resolve', 'Resolve'), ('transition', 'Transition')], max_length=16)),
                ('outcome', models.CharField(choices=[('resolved', 'Resolved'), ('transitioned', 'Transitioned'), ('not_found', 'Not found'), ('rejected', 'Rejected')], max_length=16)),
                ('requested_status', models.CharField(blank=True, max_length=32)),
                ('source', models.CharField(default='staff_scan_api', max_length=32)),
                ('message', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='productionjob',
            options={'ordering': ('-updated_at', '-created_at'), 'permissions': [('scan_productionjob', 'Can resolve production job by scan'), ('scan_transition_productionjob', 'Can transition production job by scan'), ('transition_productionjob', 'Can transition production job')]},
        ),
        migrations.AddField(
            model_name='productionjob',
            name='scan_identifier',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.RunPython(backfill_scan_identifiers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='productionjob',
            name='scan_identifier',
            field=models.CharField(default=apps.production.models.generate_production_scan_identifier, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='productionjobscanlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_job_scan_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionjobscanlog',
            name='production_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='production.productionjob'),
        ),
        migrations.AddIndex(
            model_name='productionjobscanlog',
            index=models.Index(fields=['scan_identifier', 'created_at'], name='production__scan_id_a796f5_idx'),
        ),
        migrations.AddIndex(
            model_name='productionjobscanlog',
            index=models.Index(fields=['action', 'created_at'], name='production__action_846762_idx'),
        ),
        migrations.AddIndex(
            model_name='productionjobscanlog',
            index=models.Index(fields=['production_job', 'created_at'], name='production__product_3bf81f_idx'),
        ),
    ]
