# Generated by Django 5.2.17 on 2026-08-21 11:44

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_billing_statement_freeze'),
        ('production', '0003_sync_scan_identifier_with_mo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPrintRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('printed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='staff_portal', max_length=32)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('request_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('machine_public_id_snapshot', models.UUIDField()),
                ('machine_code_snapshot', models.CharField(max_length=32)),
                ('machine_name_snapshot', models.CharField(max_length=120)),
                ('manufacturing_order_number_snapshot', models.CharField(max_length=64)),
                ('order_public_id_snapshot', models.UUIDField()),
                ('customer_public_id_snapshot', models.UUIDField()),
            ],
            options={
                'ordering': ('-printed_at', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='productionjob',
            name='machine_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='machine_assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_jobs_machine_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductionMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('manufacturer', models.CharField(blank=True, max_length=80)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('max_print_width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('active', 'Disponible'), ('maintenance', 'Maintenance'), ('retired', 'Retirée du parc')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_machines_status_changed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('code', 'name'),
                'permissions': [('manage_productionmachine', 'Can manage the DTF machine fleet'), ('assign_productionmachine', 'Can assign production jobs to DTF machines'), ('confirm_productionprint', 'Can confirm a production print')],
            },
        ),
        migrations.CreateModel(
            name='ProductionJobMachineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(default='staff_portal', max_length=32)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('machine_public_id_snapshot', models.UUIDField()),
                ('machine_code_snapshot', models.CharField(max_length=32)),
                ('machine_name_snapshot', models.CharField(max_length=120)),
                ('previous_machine_public_id_snapshot', models.UUIDField(blank=True, null=True)),
                ('previous_machine_code_snapshot', models.CharField(blank=True, max_length=32)),
                ('previous_machine_name_snapshot', models.CharField(blank=True, max_length=120)),
                ('printing_started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_machine_assignments', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_machine_assignments_ended', to=settings.AUTH_USER_MODEL)),
                ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_assignments', to='production.productionjob')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_assignments', to='production.productionmachine')),
                ('previous_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_reassignments_from', to='production.productionmachine')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='productionjob',
            name='assigned_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_jobs', to='production.productionmachine'),
        ),
        migrations.AddIndex(
            model_name='productionjob',
            index=models.Index(fields=['assigned_machine', 'status', 'updated_at'], name='production__assigne_c56808_idx'),
        ),
        migrations.AddField(
            model_name='productionprintrecord',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_records', to='production.productionjobmachineassignment'),
        ),
        migrations.AddField(
            model_name='productionprintrecord',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_records', to='production.productionmachine'),
        ),
        migrations.AddField(
            model_name='productionprintrecord',
            name='production_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_records', to='production.productionjob'),
        ),
        migrations.AddField(
            model_name='productionprintrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_print_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='productionmachine',
            index=models.Index(fields=['status', 'name'], name='production__status_4b7254_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionmachine',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='production_machine_code_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='productionjobmachineassignment',
            index=models.Index(fields=['production_job', 'created_at'], name='production__product_21a156_idx'),
        ),
        migrations.AddIndex(
            model_name='productionjobmachineassignment',
            index=models.Index(fields=['machine', 'created_at'], name='production__machine_6808b1_idx'),
        ),
        migrations.AddIndex(
            model_name='productionjobmachineassignment',
            index=models.Index(fields=['machine', 'ended_at'], name='production__machine_ebbdf7_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionjobmachineassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('production_job',), name='production_one_open_machine_assignment_per_job'),
        ),
        migrations.AddConstraint(
            model_name='productionjobmachineassignment',
            constraint=models.CheckConstraint(condition=models.Q(('previous_machine__isnull', True), models.Q(('previous_machine', models.F('machine')), _negated=True), _connector='OR'), name='production_machine_reassignment_changes_machine'),
        ),
        migrations.AddIndex(
            model_name='productionprintrecord',
            index=models.Index(fields=['production_job', 'printed_at'], name='production__product_c99bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='productionprintrecord',
            index=models.Index(fields=['machine', 'printed_at'], name='production__machine_d47a4c_idx'),
        ),
    ]
