# Generated by Django 5.2.17 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0006_remove_productionjob_of_doc_index_and_alter_issued_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionprintrecord",
            name="printed_linear_m",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Métrage linéaire figé au moment de la confirmation d’impression.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="productionprintrecord",
            index=models.Index(fields=["printed_at"], name="prod_print_record_date_idx"),
        ),
    ]
