# Generated by Django 5.2 for IDS Hub / Prenium DTF.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("order_created", "Commande créée"),
                            ("payment_captured", "Paiement confirmé"),
                            ("b2b_order_submitted", "Commande B2B transmise"),
                            ("order_priced", "Commande tarifée"),
                        ],
                        max_length=32,
                        verbose_name="Événement",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("client", "Client"), ("internal", "Équipe interne")],
                        max_length=16,
                        verbose_name="Audience",
                    ),
                ),
                ("subject_template", models.CharField(max_length=255, verbose_name="Objet")),
                ("body_template", models.TextField(verbose_name="Message")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_email_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle d’e-mail",
                "verbose_name_plural": "Modèles d’e-mails",
                "ordering": ("event", "audience"),
                "indexes": [
                    models.Index(
                        fields=["audience", "is_active"],
                        name="notif_email_aud_active_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "audience"),
                        name="uniq_notification_email_template_event_audience",
                    )
                ],
            },
        ),
    ]
