# Generated by Django 5.1.15 on 2026-07-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='event',
            field=models.CharField(choices=[('order_created', 'Commande créée'), ('payment_captured', 'Paiement confirmé'), ('b2b_order_submitted', 'Commande B2B transmise'), ('order_priced', 'Commande tarifée'), ('file_correction_requested', 'Correction fichier demandée')], max_length=32, verbose_name='Événement'),
        ),
    ]
