# Generated by Django 5.1.15 on 2026-07-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_order_lifecycle_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='event',
            field=models.CharField(choices=[('order_created', 'Commande créée'), ('payment_captured', 'Paiement confirmé'), ('order_processing', 'Commande en traitement'), ('order_ready_to_ship', 'Commande traitée'), ('order_shipped', 'Commande expédiée'), ('order_priced', 'Commande tarifée'), ('file_correction_requested', 'Correction fichier demandée'), ('access_request_email_verification', "Vérification demande d'accès"), ('access_request_submitted_internal', "Nouvelle demande d'accès"), ('access_request_approved', "Demande d'accès validée"), ('access_request_rejected', "Demande d'accès refusée"), ('account_activated', 'Compte activé'), ('customer_member_invited', 'Collaborateur invité')], max_length=48, verbose_name='Événement'),
        ),
    ]
