# Generated by Django 5.2.17 on 2026-08-13 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_defaultcustomervolumediscounttier'),
        ('notifications', '0005_order_awaiting_payment_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='event',
            field=models.CharField(choices=[('order_created', 'Commande créée'), ('payment_captured', 'Paiement confirmé'), ('order_processing', 'Commande en traitement'), ('order_ready_to_ship', 'Commande traitée'), ('order_shipped', 'Commande expédiée'), ('order_priced', 'Commande tarifée'), ('order_awaiting_payment', 'Paiement carte à effectuer'), ('file_correction_requested', 'Correction fichier demandée'), ('access_request_email_verification', "Vérification demande d'accès"), ('access_request_submitted_internal', "Nouvelle demande d'accès"), ('access_request_approved', "Demande d'accès validée"), ('access_request_rejected', "Demande d'accès refusée"), ('account_activated', 'Compte activé'), ('customer_member_invited', 'Collaborateur invité'), ('volume_discount_tier_reached', 'Palier de remise atteint')], max_length=48, verbose_name='Événement'),
        ),
        migrations.CreateModel(
            name='VolumeDiscountTierNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('month', models.DateField(verbose_name='Mois civil')),
                ('threshold_linear_m', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Seuil atteint (m linéaires)')),
                ('monthly_volume_linear_m', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Volume mensuel (m linéaires)')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Remise (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remise cumulée HT (EUR)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('skipped', 'Ignoré')], default='pending', max_length=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_discount_notifications', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Notification de palier de remise',
                'verbose_name_plural': 'Notifications de paliers de remise',
                'ordering': ('-month', '-threshold_linear_m', '-created_at'),
                'indexes': [models.Index(fields=['customer', 'month', 'status'], name='notif_customer_month_tier_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'month', 'threshold_linear_m'), name='uniq_customer_month_volume_tier_notification'), models.CheckConstraint(condition=models.Q(('threshold_linear_m__gt', 0)), name='volume_tier_notification_threshold_positive'), models.CheckConstraint(condition=models.Q(('monthly_volume_linear_m__gte', 0)), name='volume_tier_notification_volume_nonnegative'), models.CheckConstraint(condition=models.Q(('discount_percent__gt', 0), ('discount_percent__lte', 100)), name='volume_tier_notification_discount_valid')],
            },
        ),
    ]
