# Generated by Django 5.2.17 on 2026-08-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_emailtemplate_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumediscounttiernotification',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volumediscounttiernotification',
            name='delivery_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volumediscounttiernotification',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('sending', 'En cours d’envoi'), ('sent', 'Envoyé'), ('skipped', 'Ignoré'), ('failed', 'Échec d’envoi')], default='pending', max_length=12),
        ),
    ]
