# Generated by Django 5.2.17 on 2026-08-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_volumediscounttiernotification_attempt_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="event",
            field=models.CharField(
                choices=[
                    ("order_created", "Commande créée"),
                    ("payment_captured", "Paiement confirmé"),
                    ("order_processing", "Commande en traitement"),
                    ("order_ready_to_ship", "Commande traitée"),
                    ("order_shipped", "Commande expédiée"),
                    ("order_priced", "Commande tarifée"),
                    ("order_awaiting_payment", "Paiement carte à effectuer"),
                    ("file_correction_requested", "Correction fichier demandée"),
                    ("access_request_email_verification", "Vérification demande d'accès"),
                    ("access_request_submitted_internal", "Nouvelle demande d'accès"),
                    ("access_request_approved", "Demande d'accès validée"),
                    ("access_request_rejected", "Demande d'accès refusée"),
                    ("account_activated", "Compte activé"),
                    ("customer_member_invited", "Collaborateur invité"),
                    ("password_reset", "Réinitialisation du mot de passe"),
                    ("volume_discount_tier_reached", "Palier de remise atteint"),
                ],
                max_length=48,
                verbose_name="Événement",
            ),
        ),
    ]
