# Generated by Django 5.2.17 on 2026-09-08 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_accounts_st_status_8d2f1a_idx_accounts_st_status_fa0977_idx_and_more'),
        ('customers', '0018_volumediscountdashboardcopy'),
        ('notifications', '0010_order_ready_for_pickup_event'),
        ('orders', '0010_order_estimated_handover_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('endpoint_ciphertext', models.TextField()),
                ('endpoint_digest', models.CharField(max_length=64, unique=True)),
                ('p256dh_ciphertext', models.TextField()),
                ('auth_ciphertext', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField()),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('last_failure_code', models.CharField(blank=True, max_length=32)),
                ('staff_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='accounts.staffmembership')),
            ],
            options={
                'verbose_name': 'Abonnement Web Push Atelier',
                'verbose_name_plural': 'Abonnements Web Push Atelier',
                'ordering': ('-last_seen_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkshopNotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('workshop.order_submitted', 'Nouvelle commande Atelier')], max_length=64)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_workshop_notification_events', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_notification_events', to='customers.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_notification_events', to='orders.order')),
            ],
            options={
                'verbose_name': 'Événement Atelier',
                'verbose_name_plural': 'Événements Atelier',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PushDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sending', 'En cours'), ('retry', 'À réessayer'), ('sent', 'Envoyée'), ('skipped', 'Ignorée'), ('gone', 'Abonnement expiré'), ('failed', 'Échec définitif')], default='pending', max_length=12)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=32)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.staffpushsubscription')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.workshopnotificationevent')),
            ],
            options={
                'verbose_name': 'Livraison Web Push',
                'verbose_name_plural': 'Livraisons Web Push',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='staffpushsubscription',
            index=models.Index(fields=['staff_membership', 'is_active'], name='notif_push_member_active_idx'),
        ),
        migrations.AddIndex(
            model_name='staffpushsubscription',
            index=models.Index(fields=['is_active', 'last_seen_at'], name='notif_push_active_seen_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffpushsubscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('disabled_at__isnull', True), ('is_active', True)), ('is_active', False), _connector='OR'), name='notif_push_active_not_disabled'),
        ),
        migrations.AddIndex(
            model_name='workshopnotificationevent',
            index=models.Index(fields=['customer', 'created_at'], name='notif_workshop_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopnotificationevent',
            index=models.Index(fields=['event_type', 'created_at'], name='notif_workshop_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='workshopnotificationevent',
            constraint=models.UniqueConstraint(fields=('event_type', 'order'), name='uniq_workshop_event_type_order'),
        ),
        migrations.AddIndex(
            model_name='pushdelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='notif_delivery_retry_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdelivery',
            index=models.Index(fields=['event', 'status'], name='notif_delivery_event_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdelivery',
            index=models.Index(fields=['subscription', 'status'], name='notif_delivery_sub_idx'),
        ),
        migrations.AddConstraint(
            model_name='pushdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'subscription'), name='uniq_workshop_event_subscription'),
        ),
        migrations.AddConstraint(
            model_name='pushdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'sent'), _negated=True), ('delivered_at__isnull', False), _connector='OR'), name='notif_delivery_sent_at'),
        ),
        migrations.AddConstraint(
            model_name='pushdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'sending'), _negated=True), ('claimed_at__isnull', False), _connector='OR'), name='notif_delivery_claimed_at'),
        ),
    ]
