# Generated by Django 5.2.17 on 2026-09-25 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_volumediscountdashboardcopy'),
        ('notifications', '0011_workshop_web_push'),
        ('orders', '0011_order_manual_billing_adjusted_at'),
        ('pod', '0017_pod_quality_check'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workshopnotificationevent',
            name='uniq_workshop_event_type_order',
        ),
        migrations.AddField(
            model_name='workshopnotificationevent',
            name='pod_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_notification_events', to='pod.podshopifyorder'),
        ),
        migrations.AddField(
            model_name='workshopnotificationevent',
            name='pod_ready_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshop_notification_events', to='pod.podqualitycheck'),
        ),
        migrations.AlterField(
            model_name='workshopnotificationevent',
            name='event_type',
            field=models.CharField(choices=[('workshop.order_submitted', 'Nouvelle commande Atelier'), ('workshop.pod_order_qc_ready', 'Commande POD contrôlée')], max_length=64),
        ),
        migrations.AlterField(
            model_name='workshopnotificationevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_notification_events', to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='workshopnotificationevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', False), ('pod_order__isnull', True)), models.Q(('order__isnull', True), ('pod_order__isnull', False)), _connector='OR'), name='notif_workshop_event_order_xor'),
        ),
        migrations.AddConstraint(
            model_name='workshopnotificationevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'workshop.pod_order_qc_ready'), ('order__isnull', True), ('pod_order__isnull', False), ('pod_ready_check__isnull', False)), models.Q(('event_type', 'workshop.order_submitted'), ('order__isnull', False), ('pod_order__isnull', True), ('pod_ready_check__isnull', True)), _connector='OR'), name='notif_workshop_event_type_target'),
        ),
        migrations.AddConstraint(
            model_name='workshopnotificationevent',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('event_type', 'order'), name='uniq_workshop_event_type_order'),
        ),
        migrations.AddConstraint(
            model_name='workshopnotificationevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_type', 'workshop.pod_order_qc_ready')), fields=('pod_ready_check',), name='uniq_workshop_pod_ready_check'),
        ),
    ]
