# Generated by Django 5.0.6 on 2026-04-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='prospectprofile',
            new_name='prospects_p_status_df370f_idx',
            old_name='prospects_p_status_7f8a9c_idx',
        ),
        migrations.RenameIndex(
            model_name='prospectprofile',
            new_name='prospects_p_email_950529_idx',
            old_name='prospects_p_email_2b3c4d_idx',
        ),
        migrations.AlterField(
            model_name='prospectprofile',
            name='activity_type',
            field=models.CharField(choices=[('brand', 'Marque textile'), ('printer', 'Imprimeur / revendeur'), ('workshop', 'Atelier'), ('creator', 'Créateur / studio'), ('other', 'Autre')], max_length=32),
        ),
        migrations.AlterField(
            model_name='prospectprofile',
            name='monthly_volume',
            field=models.CharField(choices=[('lt10', 'Moins de 10 mètres'), ('10_50', '10 à 50 mètres'), ('50_200', '50 à 200 mètres'), ('gt200', '200 mètres et plus')], max_length=16),
        ),
        migrations.AlterField(
            model_name='prospectprofile',
            name='order_frequency',
            field=models.CharField(choices=[('punctual', 'Ponctuel'), ('monthly', 'Mensuel'), ('regular', 'Régulier'), ('intensive', 'Intensif')], max_length=16),
        ),
        migrations.AlterField(
            model_name='prospectprofile',
            name='project_timing',
            field=models.CharField(choices=[('immediate', 'Besoin immédiat'), ('ongoing', 'Projet en cours'), ('exploring', 'Exploration / veille')], max_length=32),
        ),
        migrations.AlterField(
            model_name='prospectprofile',
            name='service_interest',
            field=models.CharField(choices=[('dtf_meter', 'DTF au mètre'), ('file_prep', 'Préparation de fichier DTF'), ('both', 'Les deux'), ('unsure', 'Je ne sais pas encore')], max_length=32),
        ),
        migrations.AlterField(
            model_name='prospectprofile',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('qualified', 'Qualifié'), ('account_created', 'Compte créé'), ('converted', 'Converti')], db_index=True, default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='prospectprofile',
            name='urgency',
            field=models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée')], max_length=16),
        ),
    ]
