# Generated by Django 5.1.15 on 2026-07-14 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_profiles(apps, schema_editor):
    ProspectProfile = apps.get_model('prospects', 'ProspectProfile')
    opened_emails = set()
    for profile in ProspectProfile.objects.order_by('-created_at').iterator():
        normalized_email = (profile.email or '').strip().lower()
        updates = {'normalized_email': normalized_email}
        if profile.status in {'account_created', 'converted'} or profile.user_id:
            updates.update(status='active', is_open=False, activated_at=profile.updated_at)
        elif normalized_email and normalized_email not in opened_emails:
            updates.update(status='pending_review', is_open=True)
            opened_emails.add(normalized_email)
        else:
            updates.update(status='cancelled', is_open=False)
        ProspectProfile.objects.filter(pk=profile.pk).update(**updates)


def reverse_legacy_profiles(apps, schema_editor):
    ProspectProfile = apps.get_model('prospects', 'ProspectProfile')
    ProspectProfile.objects.filter(status='active').update(status='account_created')
    ProspectProfile.objects.exclude(status='account_created').update(status='new')


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_siren_customer_vat_number_and_more'),
        ('prospects', '0002_align_model_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospectprofile',
            options={'ordering': ('-created_at',), 'permissions': [('review_prospectprofile', 'Can approve or reject access requests')]},
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='is_open',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='normalized_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_prospect_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='siren',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='vat_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='verification_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(migrate_legacy_profiles, reverse_legacy_profiles),
        migrations.AlterField(
            model_name='prospectprofile',
            name='status',
            field=models.CharField(choices=[('pending_email_verification', 'E-mail à vérifier'), ('pending_review', 'En attente de validation'), ('needs_information', 'Informations complémentaires requises'), ('approved_pending_activation', 'Validée — activation requise'), ('active', 'Compte actif'), ('rejected', 'Refusée'), ('expired', 'Expirée'), ('cancelled', 'Annulée')], db_index=True, default='pending_email_verification', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='prospectprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('normalized_email',), name='uniq_open_prospect_normalized_email'),
        ),
    ]
