# Generated by Django 5.2.17 on 2026-09-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0003_alter_prospectprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectprofile',
            name='billing_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='billing_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='billing_city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='billing_postal_code',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
