# Generated by Django 5.0.6 on 2026-04-04 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_legacy_pricing_status(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Order.objects.all().update(pricing_status="priced")


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_b2b_deferred_billing'),
        ('customers', '0003_b2b_deferred_billing'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_mode',
            field=models.CharField(choices=[('immediate', 'Paiement à la commande'), ('deferred', 'Facturation différée')], default='immediate', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='billing.billingstatement'),
        ),
        migrations.AddField(
            model_name='order',
            name='credit_hold_status',
            field=models.CharField(choices=[('none', 'Non applicable'), ('clear', 'Encours dans la limite'), ('warning', 'Encours dépassé (alerte)'), ('blocked', 'Encours dépassé (blocage)')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='pricing_status',
            field=models.CharField(choices=[('pending', 'Prix en attente'), ('priced', 'Prix calculé'), ('failed', 'Échec calcul')], default='pending', max_length=16),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'billing_mode', 'pricing_status'], name='orders_orde_custome_b5b799_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['billing_statement', 'created_at'], name='orders_orde_billing_5199c9_idx'),
        ),
        migrations.RunPython(set_legacy_pricing_status, migrations.RunPython.noop),
    ]
