# Generated by Django 5.1.15 on 2026-04-05 01:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_b2b_deferred_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='meterage_override_linear_m',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Saisie opérateur : mètres linéaires sur la laize pour toute la commande. Surface facturable = linéaire × laize, répartie entre les fichiers au tarif.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
    ]
