# Generated by Django 5.1.15 on 2026-07-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_meterage_override_linear_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_mode',
            field=models.CharField(choices=[('immediate', 'Paiement comptant (carte bancaire)'), ('deferred', 'Encours / facturation différée')], default='immediate', max_length=16),
        ),
    ]
