# Generated by Django 5.1.15 on 2026-07-26 09:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_cancelled_atelier_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Frais d’expédition HT figés (0 si retrait atelier).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method_code',
            field=models.SlugField(blank=True, help_text='Snapshot code option livraison (pickup / standard / express).', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method_name',
            field=models.CharField(blank=True, help_text='Snapshot libellé option livraison au moment du choix.', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant TVA (comptant CB : 20 % sur sous-total HT + port).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Taux TVA appliqué (ex. 0.2000 = 20 %). 0 si encours / hors TVA.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sous-total HT lignes produit (DTF + préparation fichier).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total dû / encaissé : subtotal + shipping + tax.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
