# Generated by Django 5.1.15 on 2026-04-01 22:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUploadInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('error', 'Error')], default='ok', max_length=16)),
                ('summary_message', models.CharField(blank=True, max_length=255)),
                ('file_kind', models.CharField(blank=True, max_length=32)),
                ('file_extension', models.CharField(blank=True, max_length=32)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField()),
                ('order_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='uploads.orderupload')),
            ],
            options={
                'ordering': ('-checked_at', '-created_at'),
                'indexes': [models.Index(fields=['status', 'checked_at'], name='uploads_ord_status_14eb25_idx'), models.Index(fields=['order_upload', 'status'], name='uploads_ord_order_u_c01126_idx')],
            },
        ),
    ]
