# Generated by Django 5.1.15 on 2026-04-01 22:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_orderuploadinspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderuploadinspection',
            name='checked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
