# Generated by Django 5.1.15 on 2026-04-02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("uploads", "0003_alter_orderuploadinspection_checked_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDriveFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
                ),
                ("shared_drive_id", models.CharField(max_length=255)),
                ("relative_path", models.CharField(max_length=512)),
                ("order_folder_id", models.CharField(max_length=255)),
                ("folder_ids", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drive_folder",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["order"], name="uploads_ord_order_i_a6770a_idx"),
                    models.Index(
                        fields=["shared_drive_id", "order_folder_id"],
                        name="uploads_ord_shared__722293_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderUploadDriveSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("drive_filename", models.CharField(blank=True, max_length=255)),
                ("remote_folder_id", models.CharField(blank=True, max_length=255)),
                ("drive_file_id", models.CharField(blank=True, max_length=255)),
                ("last_error", models.CharField(blank=True, max_length=255)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                (
                    "drive_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_syncs",
                        to="uploads.orderdrivefolder",
                    ),
                ),
                (
                    "order_upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drive_sync",
                        to="uploads.orderupload",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["status", "last_attempt_at"],
                        name="uploads_ord_status_b1f90f_idx",
                    ),
                    models.Index(
                        fields=["order_upload", "status"],
                        name="uploads_ord_order_u_56bfca_idx",
                    ),
                ],
            },
        ),
    ]
