# Generated by Django 5.1.15 on 2026-04-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0004_drive_sync_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="orderdrivefolder",
            old_name="uploads_ord_order_i_a6770a_idx",
            new_name="uploads_ord_order_i_755dba_idx",
        ),
        migrations.RenameIndex(
            model_name="orderdrivefolder",
            old_name="uploads_ord_shared__722293_idx",
            new_name="uploads_ord_shared__3a6509_idx",
        ),
        migrations.RenameIndex(
            model_name="orderuploaddrivesync",
            old_name="uploads_ord_status_b1f90f_idx",
            new_name="uploads_ord_status_ae5663_idx",
        ),
        migrations.RenameIndex(
            model_name="orderuploaddrivesync",
            old_name="uploads_ord_order_u_56bfca_idx",
            new_name="uploads_ord_order_u_a8fb34_idx",
        ),
    ]
