# Generated by Django 5.0.6 on 2026-04-04 13:06

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_b2b_deferred_billing'),
        ('uploads', '0005_rename_drive_sync_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderupload',
            options={'ordering': ('sort_order', 'created_at')},
        ),
        migrations.AddField(
            model_name='orderupload',
            name='line_total_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='orderupload',
            name='meterage_sqm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='orderupload',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='orderupload',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderupload',
            name='support_color_hex',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur attendue au format #RRVVBB.', regex='^$|^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='orderupload',
            name='unit_price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='orderupload',
            index=models.Index(fields=['order', 'sort_order'], name='uploads_ord_order_i_147f32_idx'),
        ),
    ]
