# Generated by Django 5.1.15 on 2026-04-05 00:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0008_orderupload_meterage_override_linear_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupload',
            name='meterage_override_linear_m',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Saisie opérateur : mètres linéaires sur la laize (par exemplaire). Facturation m² = linéaire × laize × quantité.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='orderupload',
            name='meterage_override_sqm',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Ancienne saisie opérateur en m² (rétrocompatibilité). Préférer meterage_override_linear_m.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
    ]
