# Generated by Django 5.1.15 on 2026-07-11 16:29

import apps.uploads.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_b2b_order_projects_enabled'),
        ('uploads', '0009_alter_orderupload_meterage_override_linear_m_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='customers.customer')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(max_length=500, upload_to=apps.uploads.models.asset_version_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('analysis_status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'Analyse en cours'), ('ready', 'Analysé'), ('warning', 'À vérifier'), ('failed', 'Échec')], default='pending', max_length=16)),
                ('analysis_error', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='uploads.asset')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_versions', to='customers.customer')),
                ('replaced_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_versions', to='uploads.assetversion')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_asset_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-version_number',),
                'permissions': [('analyze_assetversion', 'Can analyze asset versions')],
            },
        ),
        migrations.CreateModel(
            name='AssetAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('dpi_x', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dpi_y', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('has_alpha', models.BooleanField(blank=True, null=True)),
                ('probable_white_background', models.BooleanField(blank=True, null=True)),
                ('thumbnail', models.FileField(blank=True, max_length=500, upload_to=apps.uploads.models.asset_thumbnail_path)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_analyses', to='customers.customer')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='uploads.assetversion')),
            ],
            options={
                'ordering': ('-analyzed_at', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_assets', to='uploads.assetversion'),
        ),
        migrations.AddField(
            model_name='orderupload',
            name='asset_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_order_upload', to='uploads.assetversion'),
        ),
        migrations.AddIndex(
            model_name='assetversion',
            index=models.Index(fields=['customer', 'analysis_status', 'created_at'], name='uploads_ass_custome_b527b8_idx'),
        ),
        migrations.AddIndex(
            model_name='assetversion',
            index=models.Index(fields=['customer', 'sha256'], name='uploads_ass_custome_0ecdca_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetversion',
            constraint=models.UniqueConstraint(fields=('customer', 'asset', 'version_number'), name='uniq_asset_version_number'),
        ),
        migrations.AddIndex(
            model_name='assetanalysis',
            index=models.Index(fields=['customer', 'analyzed_at'], name='uploads_ass_custome_ec396c_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['customer', 'is_archived', 'updated_at'], name='uploads_ass_custome_3c864e_idx'),
        ),
    ]
