# Generated by Django 5.1.15 on 2026-07-14 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0014_assetanalysis_semi_transparency_overlay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUploadReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'À contrôler'), ('approved', 'Approuvé pour production'), ('changes_requested', 'Correction demandée')], default='pending', max_length=24)),
                ('reason_code', models.CharField(blank=True, choices=[('low_resolution', 'Résolution insuffisante'), ('wrong_dimensions', 'Dimensions incorrectes'), ('background', 'Fond ou transparence à corriger'), ('corrupted', 'Fichier illisible ou corrompu'), ('incomplete', 'Contenu incomplet'), ('other', 'Autre motif')], max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('client_notified_at', models.DateTimeField(blank=True, null=True)),
                ('order_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atelier_review', to='uploads.orderupload')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_order_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-reviewed_at', '-updated_at'),
                'permissions': [('review_orderupload', 'Can review order uploads for production')],
                'indexes': [models.Index(fields=['status', 'reviewed_at'], name='uploads_ord_status_ee0f3f_idx'), models.Index(fields=['order_upload', 'status'], name='uploads_ord_order_u_89eedf_idx')],
            },
        ),
    ]
