# Generated by Django 5.1.15 on 2026-07-26 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0016_orderupload_production_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupload',
            name='asset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_uploads', to='uploads.assetversion'),
        ),
    ]
