# Generated by Django 5.2.17 on 2026-09-17 11:40

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_order_estimated_handover_date"),
        ("uploads", "0021_orderupload_external_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orderupload",
            name="external_visual_count",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="orderupload",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("external_visual_count__gte", 1), ("external_visual_count__lte", 10000)
                ),
                name="uploads_external_visual_count_range",
            ),
        ),
    ]
