# Generated by Django 5.1.15 on 2026-04-02 16:38

import apps.billing.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(choices=[('paypal', 'PayPal')], default='paypal', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('captured', 'Captured'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(max_length=3)),
                ('paypal_order_id', models.CharField(blank=True, max_length=255)),
                ('paypal_capture_id', models.CharField(blank=True, max_length=255)),
                ('approval_url', models.URLField(blank=True, max_length=2048)),
                ('source', models.CharField(default='client_api', max_length=32)),
                ('request_snapshot', models.JSONField(blank=True, default=dict)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': [('confirm_payment', 'Can confirm payment')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('void', 'Void')], default='issued', max_length=16)),
                ('invoice_number', models.CharField(max_length=64, unique=True)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(max_length=3)),
                ('billing_name', models.CharField(blank=True, max_length=255)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('file', models.FileField(blank=True, max_length=500, upload_to=apps.billing.models.invoice_document_path)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_mime_type', models.CharField(blank=True, max_length=128)),
                ('source', models.CharField(default='backend_capture', max_length=32)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.payment')),
            ],
            options={
                'ordering': ('-issued_at', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status', 'created_at'], name='billing_pay_order_i_32fc27_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'updated_at'], name='billing_pay_status_696887_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('paypal_order_id', ''), _negated=True), fields=('paypal_order_id',), name='uniq_payment_paypal_order_id_non_empty'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('paypal_capture_id', ''), _negated=True), fields=('paypal_capture_id',), name='uniq_payment_paypal_capture_id_non_empty'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'issued_at'], name='billing_inv_status_2156f7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['order', 'status'], name='billing_inv_order_i_51aad7_idx'),
        ),
    ]
