# Generated by Django 5.0.6 on 2026-04-04 13:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('customers', '0003_b2b_deferred_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('issued', 'Emise'), ('paid', 'Payee')], default='draft', max_length=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_statements', to='customers.customer')),
            ],
            options={
                'ordering': ('-period_end', '-created_at'),
                'indexes': [models.Index(fields=['customer', 'status', 'period_end'], name='billing_bil_custome_3a0198_idx')],
            },
        ),
    ]
