# Generated by Django 5.1.15 on 2026-04-24 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_paid_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-issued_at', '-created_at'), 'permissions': [('mark_invoice_paid', 'Marquer une facture comme payée (virement)')]},
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='billing_inv_paid_at_a017a2_idx',
            old_name='billing_inv_paid_at_8a1b2c_idx',
        ),
    ]
