# Generated by Django 5.1.15 on 2026-07-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_payment_stripe_provider'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='billing_pay_provide_5b0d17_idx',
            old_name='billing_pay_provide_a1b2c3_idx',
        ),
    ]
