# Generated by Django 5.1.15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0008_billing_statement_snapshots"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGatewaySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
                ),
                ("paypal_enabled", models.BooleanField(default=False)),
                ("stripe_enabled", models.BooleanField(default=False)),
                ("paypal_client_id", models.CharField(blank=True, max_length=255)),
                ("paypal_client_secret_encrypted", models.TextField(blank=True)),
                ("paypal_webhook_id", models.CharField(blank=True, max_length=255)),
                ("stripe_publishable_key", models.CharField(blank=True, max_length=255)),
                ("stripe_secret_key_encrypted", models.TextField(blank=True)),
                ("stripe_webhook_secret_encrypted", models.TextField(blank=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_payment_gateway_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Réglages paiements en ligne",
                "verbose_name_plural": "Réglages paiements en ligne",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("singleton_key", 1)),
                        name="payment_gateway_settings_singleton_key_one",
                    ),
                ],
            },
        ),
    ]
