# Generated by Django 5.2.17 on 2026-09-18 21:06

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def assert_no_ambiguous_payment_history(apps, schema_editor):
    Payment = apps.get_model("billing", "Payment")
    duplicates = list(
        Payment.objects.using(schema_editor.connection.alias)
        .filter(status__in=("pending", "approved", "captured"))
        .values("order_id")
        .annotate(payment_count=Count("id"))
        .filter(payment_count__gt=1)
        .values_list("order_id", flat=True)[:20]
    )
    if duplicates:
        raise RuntimeError(
            "Migration billing 0011 bloquée : paiements encore payables ou déjà "
            f"capturés multiples pour les commandes {duplicates}. Rapprocher et "
            "fermer les sessions distantes avant d'ajouter la contrainte unique."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_payment_source_max_length'),
        ('orders', '0010_order_estimated_handover_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(assert_no_ambiguous_payment_history, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(status__in=("pending", "approved", "captured")),
                fields=("order",),
                name="uniq_payable_or_captured_payment_per_order",
            ),
        ),
    ]
