# Generated by Django 5.1.15 on 2026-04-01 18:22

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('service_type', models.CharField(choices=[('dtf_transfer', 'DTF au metre'), ('file_preparation', 'Preparation de fichier')], max_length=32)),
                ('unit', models.CharField(choices=[('linear_meter', 'Metre lineaire'), ('fixed', 'Forfait')], max_length=32)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'name'),
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='catalog_cat_is_acti_2bbed4_idx'), models.Index(fields=['service_type', 'is_active'], name='catalog_cat_service_85a6e7_idx')],
            },
        ),
    ]
