# Generated by Django 5.2 on 2026-08-23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="BrandThemeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
                ),
                (
                    "theme_key",
                    models.CharField(
                        choices=[("octostitch_light", "Clair chaleureux")],
                        default="octostitch_light",
                        editable=False,
                        max_length=32,
                        verbose_name="Univers visuel",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#FF8775",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Saisissez une couleur hexadécimale complète, "
                                    "par exemple #FF8775."
                                ),
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="Couleur primaire",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#A83BC4",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Saisissez une couleur hexadécimale complète, "
                                    "par exemple #FF8775."
                                ),
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="Couleur secondaire",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_brand_theme_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Identité visuelle du site",
                "verbose_name_plural": "Identité visuelle du site",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("singleton_key", 1)),
                        name="brand_theme_singleton_key_one",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("theme_key", "octostitch_light")),
                        name="brand_theme_key_supported",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("primary_color__regex", "^#[0-9A-F]{6}$")),
                        name="brand_theme_primary_hex",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("secondary_color__regex", "^#[0-9A-F]{6}$")),
                        name="brand_theme_secondary_hex",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("primary_color", models.F("secondary_color")), _negated=True
                        ),
                        name="brand_theme_colors_distinct",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="brand_theme_version_positive",
                    ),
                ],
            },
        ),
    ]
