# Generated by Django 5.1.15 on 2026-07-15 17:35

import apps.gang_sheets.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b2b_order_projects', '0004_b2borderprojectitem_support_color_hex'),
        ('customers', '0008_customer_siren_customer_vat_number_and_more'),
        ('orders', '0003_order_meterage_override_linear_m'),
        ('uploads', '0016_orderupload_production_specs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GangSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('rendering', 'Rendu en cours'), ('ready', 'Rendu prêt'), ('validated', 'Validée'), ('render_failed', 'Échec du rendu')], default='draft', max_length=24)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('maximum_height_mm', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('height_step_mm', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('margin_mm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('item_spacing_mm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('surface_sqm', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit_price_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estimated_price_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('preview_file', models.FileField(blank=True, max_length=500, upload_to=apps.gang_sheets.models.gang_sheet_preview_path)),
                ('final_file', models.FileField(blank=True, max_length=500, upload_to=apps.gang_sheets.models.gang_sheet_final_path)),
                ('render_error', models.CharField(blank=True, max_length=255)),
                ('render_requested_at', models.DateTimeField(blank=True, null=True)),
                ('rendered_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gang_sheets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gang_sheets', to='customers.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gang_sheets', to='orders.order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gang_sheets', to='b2b_order_projects.b2borderproject')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_gang_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'permissions': [('download_final_gangsheet', 'Can download final production gang sheet'), ('configure_gangsheet', 'Can configure gang sheet generator')],
            },
        ),
        migrations.CreateModel(
            name='GangSheetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('x_mm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('y_mm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('rotation', models.PositiveSmallIntegerField(choices=[(0, '0°'), (90, '90°'), (180, '180°'), (270, '270°')], default=0)),
                ('z_index', models.PositiveIntegerField(default=1)),
                ('asset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gang_sheet_items', to='uploads.assetversion')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gang_sheet_items', to='customers.customer')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gang_sheets.gangsheet')),
            ],
            options={
                'ordering': ('z_index', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='GangSheetSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('roll_width_mm', models.DecimalField(decimal_places=2, default=Decimal('550.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('100.00')), django.core.validators.MaxValueValidator(Decimal('2000.00'))], verbose_name='Laize utile (mm)')),
                ('margin_mm', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Marge de sécurité (mm)')),
                ('item_spacing_mm', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Espacement entre visuels (mm)')),
                ('minimum_height_mm', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))], verbose_name='Hauteur minimale (mm)')),
                ('maximum_height_mm', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))], verbose_name='Hauteur maximale (mm)')),
                ('height_step_mm', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name="Pas d'arrondi de hauteur (mm)")),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_gang_sheet_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réglages Gang Sheet',
                'verbose_name_plural': 'Réglages Gang Sheet',
            },
        ),
        migrations.AddIndex(
            model_name='gangsheet',
            index=models.Index(fields=['customer', 'status', 'updated_at'], name='gang_sheets_custome_1868d0_idx'),
        ),
        migrations.AddIndex(
            model_name='gangsheet',
            index=models.Index(fields=['customer', 'project', 'created_at'], name='gang_sheets_custome_00397b_idx'),
        ),
        migrations.AddIndex(
            model_name='gangsheet',
            index=models.Index(fields=['order', 'status'], name='gang_sheets_order_i_011c7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='gangsheet',
            constraint=models.CheckConstraint(condition=models.Q(('width_mm__gt', 0)), name='gangsheet_width_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='gangsheet',
            constraint=models.CheckConstraint(condition=models.Q(('height_mm__gt', 0)), name='gangsheet_height_gt_0'),
        ),
        migrations.AddIndex(
            model_name='gangsheetitem',
            index=models.Index(fields=['customer', 'sheet', 'z_index'], name='gang_sheets_custome_2f45f9_idx'),
        ),
        migrations.AddIndex(
            model_name='gangsheetitem',
            index=models.Index(fields=['customer', 'asset_version'], name='gang_sheets_custome_5d6a59_idx'),
        ),
        migrations.AddConstraint(
            model_name='gangsheetitem',
            constraint=models.CheckConstraint(condition=models.Q(('width_mm__gt', 0)), name='gangitem_width_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='gangsheetitem',
            constraint=models.CheckConstraint(condition=models.Q(('height_mm__gt', 0)), name='gangitem_height_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='gangsheetitem',
            constraint=models.UniqueConstraint(fields=('sheet', 'z_index'), name='uniq_gangitem_sheet_z'),
        ),
    ]
