# Generated by Django 5.1.15 on 2026-07-15 17:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gang_sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gangsheet',
            name='minimum_height_mm',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
