# Generated by Django 5.1.15 on 2026-07-15 20:11

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_project_assets(apps, schema_editor):
    GangSheet = apps.get_model("gang_sheets", "GangSheet")
    GangSheetSourceAsset = apps.get_model("gang_sheets", "GangSheetSourceAsset")
    ProjectItem = apps.get_model("b2b_order_projects", "B2BOrderProjectItem")
    rows = []
    for sheet in GangSheet.objects.exclude(project_id=None).iterator():
        seen = set()
        items = ProjectItem.objects.filter(
            project_id=sheet.project_id,
            customer_id=sheet.customer_id,
            asset_id__isnull=False,
        ).order_by("sort_order", "created_at")
        for item in items.iterator():
            if item.asset_id in seen:
                continue
            seen.add(item.asset_id)
            rows.append(
                GangSheetSourceAsset(
                    customer_id=sheet.customer_id,
                    sheet_id=sheet.id,
                    asset_id=item.asset_id,
                    width_mm=item.width_mm,
                    height_mm=item.height_mm,
                    sort_order=len(seen),
                )
            )
    GangSheetSourceAsset.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_order_projects', '0004_b2borderprojectitem_support_color_hex'),
        ('customers', '0008_customer_siren_customer_vat_number_and_more'),
        ('gang_sheets', '0002_gangsheet_minimum_height_mm'),
        ('uploads', '0016_orderupload_production_specs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gangsheet',
            name='production_asset',
            field=models.OneToOneField(blank=True, help_text='PDF final injecté dans le projet de commande après validation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_gang_sheet', to='uploads.asset'),
        ),
        migrations.AlterField(
            model_name='gangsheet',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gang_sheets', to='b2b_order_projects.b2borderproject'),
        ),
        migrations.CreateModel(
            name='GangSheetSourceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_gang_sheet_source_assets', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gang_sheet_sources', to='uploads.asset')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gang_sheet_source_assets', to='customers.customer')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_assets', to='gang_sheets.gangsheet')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
                'indexes': [models.Index(fields=['customer', 'sheet', 'sort_order'], name='gang_sheets_custome_ae49eb_idx'), models.Index(fields=['customer', 'asset'], name='gang_sheets_custome_aa7dde_idx')],
                'constraints': [models.UniqueConstraint(fields=('sheet', 'asset'), name='uniq_gang_source_asset'), models.CheckConstraint(condition=models.Q(models.Q(('height_mm__isnull', True), ('width_mm__isnull', True)), models.Q(('height_mm__isnull', False), ('width_mm__isnull', False)), _connector='OR'), name='gang_source_dimensions_pair')],
            },
        ),
        migrations.RunPython(backfill_project_assets, migrations.RunPython.noop),
    ]
