# Generated by Django 5.2.17 on 2026-09-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gang_sheets", "0010_alter_gangsheetitem_text_size_mm"),
    ]

    operations = [
        migrations.AddField(
            model_name="gangsheetsourceasset",
            name="auto_placement_error",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="gangsheetsourceasset",
            name="auto_placement_status",
            field=models.CharField(
                choices=[
                    ("manual", "Placement manuel"),
                    ("awaiting_analysis", "En attente d’analyse"),
                    ("placed", "Placé automatiquement"),
                    ("no_space", "Aucun emplacement libre"),
                ],
                default="manual",
                max_length=24,
            ),
        ),
    ]
