# Generated by Django 5.1.15 on 2026-04-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',)},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
