# Generated by Django 5.1.15 on 2026-04-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'permissions': [('access_staff_portal', 'Can access the staff portal')]},
        ),
        migrations.AddField(
            model_name='user',
            name='staff_mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_mfa_required',
            field=models.BooleanField(default=False),
        ),
    ]
