# Generated by Django 5.2.17 on 2026-08-31 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffmembership_staffinivation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffinvitation',
            new_name='accounts_st_status_fa0977_idx',
            old_name='accounts_st_status_8d2f1a_idx',
        ),
        migrations.RenameIndex(
            model_name='staffinvitation',
            new_name='accounts_st_email_aa8df3_idx',
            old_name='accounts_st_email_91ac3b_idx',
        ),
        migrations.RenameIndex(
            model_name='staffmembership',
            new_name='accounts_st_role_cd4053_idx',
            old_name='accounts_st_role_4b0f0d_idx',
        ),
    ]
