# Generated by Django 5.2.17 on 2026-08-30 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name', 'sku'),
                'indexes': [models.Index(fields=['is_active', 'name'], name='pod_blank_is_acti_320903_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrintTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('rip_directory', models.CharField(default='02_rip', max_length=64)),
                ('export_extension', models.CharField(default='.png', max_length=16)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'name'),
                'permissions': [('access_pod_atelier', 'Can access POD atelier catalog and warehouse'), ('manage_pod_catalog', 'Can manage POD techniques and blanks')],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='pod_printte_is_acti_73f3fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlankVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('size_label', models.CharField(max_length=32)),
                ('color_name', models.CharField(max_length=64)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='pod.blank')),
            ],
            options={
                'ordering': ('size_label', 'color_name', 'sku'),
                'indexes': [models.Index(fields=['blank', 'is_active'], name='pod_blankva_blank_i_059ce7_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlankPlacementCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('placement', models.CharField(choices=[('front', 'Devant'), ('back', 'Dos'), ('left_chest', 'Cœur'), ('right_chest', 'Poitrine droite'), ('sleeve_left', 'Manche gauche'), ('sleeve_right', 'Manche droite'), ('collar', 'Col'), ('other', 'Autre')], max_length=32)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_capabilities', to='pod.blank')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blank_capabilities', to='pod.printtechnique')),
            ],
            options={
                'ordering': ('blank_id', 'placement', 'technique_id'),
                'indexes': [models.Index(fields=['blank', 'is_active'], name='pod_blankpl_blank_i_9c6c9a_idx')],
                'constraints': [models.UniqueConstraint(fields=('blank', 'placement', 'technique'), name='pod_blank_placement_technique_uniq')],
            },
        ),
    ]
