# Generated by Django 5.2.17 on 2026-08-30 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('shop_domain', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='IdsVariantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('mode', models.CharField(choices=[('unmanaged', 'Non géré'), ('pod', 'POD'), ('on_stock', 'Produit fini'), ('virtual', 'Virtuel'), ('disabled', 'Désactivé')], default='unmanaged', max_length=16)),
                ('finished_sku', models.CharField(blank=True, default='', max_length=80)),
                ('staff_locked', models.BooleanField(default=False, help_text='Si actif, le marchand Shopify ne peut pas modifier la config.')),
                ('blank_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_configs', to='pod.blankvariant')),
            ],
        ),
        migrations.CreateModel(
            name='PodRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('variant_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='pod.idsvariantconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PodRecipeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_templates', to='pod.blank')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_templates', to='pod.shopifystore')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ShopifyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('external_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('handle', models.SlugField(blank=True, max_length=255)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pod.shopifystore')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ShopifyVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('external_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('option1', models.CharField(blank=True, max_length=120)),
                ('option2', models.CharField(blank=True, max_length=120)),
                ('option3', models.CharField(blank=True, max_length=120)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='pod.shopifyproduct')),
            ],
            options={
                'ordering': ('title', 'sku'),
            },
        ),
        migrations.AddField(
            model_name='idsvariantconfig',
            name='variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ids_config', to='pod.shopifyvariant'),
        ),
        migrations.CreateModel(
            name='PodRecipeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('placement', models.CharField(choices=[('front', 'Devant'), ('back', 'Dos'), ('left_chest', 'Cœur'), ('right_chest', 'Poitrine droite'), ('sleeve_left', 'Manche gauche'), ('sleeve_right', 'Manche droite'), ('collar', 'Col'), ('other', 'Autre')], max_length=32)),
                ('is_enabled', models.BooleanField(default=True)),
                ('print_reference', models.CharField(blank=True, default='', help_text='Référence fichier HD (nom RIP ou public_id AssetVersion).', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='pod.podrecipe')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_slots', to='pod.printtechnique')),
            ],
            options={
                'ordering': ('display_order', 'placement', 'technique_id'),
                'constraints': [models.UniqueConstraint(fields=('recipe', 'placement', 'technique'), name='pod_recipe_slot_uniq')],
            },
        ),
        migrations.CreateModel(
            name='PodRecipeTemplateSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('placement', models.CharField(choices=[('front', 'Devant'), ('back', 'Dos'), ('left_chest', 'Cœur'), ('right_chest', 'Poitrine droite'), ('sleeve_left', 'Manche gauche'), ('sleeve_right', 'Manche droite'), ('collar', 'Col'), ('other', 'Autre')], max_length=32)),
                ('print_reference', models.CharField(blank=True, default='', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_slots', to='pod.printtechnique')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='pod.podrecipetemplate')),
            ],
            options={
                'ordering': ('display_order', 'placement', 'technique_id'),
                'constraints': [models.UniqueConstraint(fields=('template', 'placement', 'technique'), name='pod_recipe_template_slot_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='shopifyproduct',
            index=models.Index(fields=['store', 'title'], name='pod_shopify_store_i_90bc33_idx'),
        ),
        migrations.AddConstraint(
            model_name='shopifyproduct',
            constraint=models.UniqueConstraint(fields=('store', 'external_id'), name='pod_shopify_product_store_external_uniq'),
        ),
        migrations.AddConstraint(
            model_name='podrecipetemplate',
            constraint=models.UniqueConstraint(fields=('name', 'blank', 'store'), name='pod_recipe_template_name_blank_store_uniq', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='shopifyvariant',
            index=models.Index(fields=['product', 'sku'], name='pod_shopify_product_d2b5eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='shopifyvariant',
            constraint=models.UniqueConstraint(fields=('product', 'external_id'), name='pod_shopify_variant_product_external_uniq'),
        ),
        migrations.AddIndex(
            model_name='idsvariantconfig',
            index=models.Index(fields=['mode'], name='pod_idsvari_mode_2e8a79_idx'),
        ),
    ]
