# Generated by Django 5.2.17 on 2026-08-30 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod', '0002_shopify_variant_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PodRipLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=48, unique=True)),
                ('status', models.CharField(choices=[('prepared', 'Prêt RIP'), ('failed', 'Échec préparation')], default='prepared', max_length=16)),
                ('nas_relative_path', models.CharField(max_length=255)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_pod_rip_lots', to=settings.AUTH_USER_MODEL)),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rip_lots', to='pod.printtechnique')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PodRipWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('shopify_order_number', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'En file RIP'), ('included', 'Inclus dans un lot'), ('skipped', 'Ignoré (config incomplète)')], default='queued', max_length=16)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=255)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rip_work_items', to='pod.shopifystore')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rip_work_items', to='pod.shopifyvariant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PodRipLotFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('placement', models.CharField(max_length=32)),
                ('filename', models.CharField(max_length=255)),
                ('source_print_reference', models.CharField(max_length=255)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pod.podriplot')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pod.printtechnique')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rip_lot_files', to='pod.shopifyvariant')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rip_files', to='pod.podripworkitem')),
            ],
            options={
                'ordering': ('filename',),
            },
        ),
        migrations.AddIndex(
            model_name='podripworkitem',
            index=models.Index(fields=['status', 'created_at'], name='pod_podripw_status_0acd74_idx'),
        ),
        migrations.AddConstraint(
            model_name='podriplotfile',
            constraint=models.UniqueConstraint(fields=('lot', 'filename'), name='pod_rip_lot_filename_uniq'),
        ),
    ]
