# Generated by Django 5.2.17 on 2026-08-30 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod', '0003_rip_lots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='webhook_secret',
            field=models.CharField(blank=True, default='', help_text='Secret HMAC Shopify (jamais exposé en front).', max_length=128),
        ),
        migrations.CreateModel(
            name='PodUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('scan_identifier', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('waiting_press', 'Attente pose'), ('pressed', 'Posé'), ('issue', 'Incident')], default='waiting_press', max_length=24)),
                ('of_relative_path', models.CharField(blank=True, default='', max_length=255)),
                ('label_relative_path', models.CharField(blank=True, default='', max_length=255)),
                ('pressed_at', models.DateTimeField(blank=True, null=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='pod.podriplot')),
                ('pressed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pressed_pod_units', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pod_units', to='pod.shopifyvariant')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='pod.podripworkitem')),
            ],
            options={
                'ordering': ('scan_identifier',),
                'constraints': [models.UniqueConstraint(fields=('work_item', 'sequence'), name='pod_unit_work_item_sequence_uniq')],
            },
        ),
    ]
