# Generated by Django 5.2.17 on 2026-08-30 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod', '0004_pod_units_webhook_stock_movements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyWebhookReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('webhook_id', models.CharField(max_length=128, unique=True)),
                ('shop_domain', models.CharField(max_length=255)),
                ('topic', models.CharField(default='orders/create', max_length=64)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
