# Generated by Django 5.2.17 on 2026-09-23 17:52

import apps.pod.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod', '0010_pod_pick_line_voided'),
    ]

    operations = [
        migrations.AddField(
            model_name='blank',
            name='photo',
            field=models.ImageField(blank=True, max_length=512, upload_to=apps.pod.models._blank_photo_upload_to),
        ),
        migrations.AddField(
            model_name='blank',
            name='photo_thumb',
            field=models.ImageField(blank=True, max_length=512, upload_to=apps.pod.models._blank_photo_thumb_upload_to),
        ),
        migrations.AddField(
            model_name='blankvariant',
            name='photo',
            field=models.ImageField(blank=True, max_length=512, upload_to=apps.pod.models._blank_variant_photo_upload_to),
        ),
        migrations.AddField(
            model_name='blankvariant',
            name='photo_thumb',
            field=models.ImageField(blank=True, max_length=512, upload_to=apps.pod.models._blank_variant_photo_thumb_upload_to),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='image_external_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='shopifyproduct',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='shopifyvariant',
            name='image_external_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='shopifyvariant',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=512),
        ),
    ]
