# Generated by Django 5.2.17 on 2026-09-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("pod", "0011_catalog_photos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="podpicksessionline",
            name="reservation_status",
            field=models.CharField(
                choices=[
                    ("untracked", "Non réservé"),
                    ("reserved", "Réservé"),
                    ("picked", "Prélevé"),
                    ("released", "Libéré"),
                ],
                db_index=True,
                default="untracked",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="podpicksessionline",
            name="stock_balance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pod_pick_lines",
                to="inventory.stockbalance",
            ),
        ),
        migrations.AddField(
            model_name="podpicksessionline",
            name="reserved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podpicksessionline",
            name="reserved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reserved_pod_pick_lines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="podpicksessionline",
            name="picked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podpicksessionline",
            name="picked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="picked_pod_pick_lines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="podpicksessionline",
            name="released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podpicksessionline",
            name="released_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="released_pod_pick_lines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
