# Generated by Django 5.2.17 on 2026-09-24

import django.db.models.deletion
from django.db import migrations, models


def _column_names(schema_editor, table: str) -> set[str]:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table)
    return {column.name for column in description}


def add_shopify_store_customer_if_missing(apps, schema_editor):
    """Idempotent: some envs already have ShopifyStore.customer outside this migration."""
    if "customer_id" in _column_names(schema_editor, "pod_shopifystore"):
        return
    Customer = apps.get_model("customers", "Customer")
    field = models.ForeignKey(
        Customer,
        null=True,
        blank=True,
        on_delete=django.db.models.deletion.PROTECT,
        related_name="pod_shopify_stores",
    )
    field.set_attributes_from_name("customer")
    schema_editor.add_field(apps.get_model("pod", "ShopifyStore"), field)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0018_volumediscountdashboardcopy"),
        ("pod", "0013_webhook_receipt_scope"),
        ("uploads", "0022_external_visual_count"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="shopifystore",
                    name="customer",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pod_shopify_stores",
                        to="customers.customer",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_shopify_store_customer_if_missing, noop_reverse),
            ],
        ),
        migrations.AddField(
            model_name="podrecipeslot",
            name="source_asset_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pod_recipe_slots",
                to="uploads.assetversion",
            ),
        ),
        migrations.AddField(
            model_name="podriplot",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pod_rip_lots",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="podriplotfile",
            name="source_asset_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pod_rip_files",
                to="uploads.assetversion",
            ),
        ),
        migrations.AddField(
            model_name="podpicksession",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pod_pick_sessions",
                to="customers.customer",
            ),
        ),
    ]
