# Generated by Django 5.2.17 on 2026-09-25 06:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0018_volumediscountdashboardcopy"),
        ("pod", "0015_durable_webhook_inbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="podripworkitem",
            name="shopify_line_item_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name="PodShopifyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("external_order_id", models.CharField(max_length=64)),
                ("order_number", models.CharField(max_length=64)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pod_shopify_orders",
                        to="customers.customer",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pod_orders",
                        to="pod.shopifystore",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="podripworkitem",
            name="shopify_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_items",
                to="pod.podshopifyorder",
            ),
        ),
        migrations.AddIndex(
            model_name="podripworkitem",
            index=models.Index(
                fields=["store", "shopify_order"], name="pod_podripw_store_i_95dc97_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="podripworkitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("shopify_line_item_id__isnull", True), ("shopify_order__isnull", True)
                    ),
                    models.Q(
                        ("shopify_line_item_id__isnull", False), ("shopify_order__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="pod_rip_item_shopify_identity_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="podripworkitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("shopify_line_item_id__isnull", False), ("shopify_order__isnull", False)
                ),
                fields=("shopify_order", "shopify_line_item_id"),
                name="pod_rip_item_shopify_identity_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="podshopifyorder",
            index=models.Index(
                fields=["customer", "created_at"], name="pod_podshop_custome_331615_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="podshopifyorder",
            constraint=models.UniqueConstraint(
                fields=("store", "external_order_id"), name="pod_shopify_order_store_external_uniq"
            ),
        ),
    ]
