# Generated by Django 5.2.17 on 2026-09-28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pod", "0018_blank_marking_options"),
        ("uploads", "0022_external_visual_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodDriveHdSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("drive_file_id", models.CharField(max_length=255)),
                ("canonical_url", models.URLField(max_length=512)),
                ("original_filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=127)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("md5_checksum", models.CharField(max_length=32)),
                ("drive_version", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Import en attente"),
                            ("importing", "Import en cours"),
                            ("ready", "Importé"),
                            ("failed", "Échec"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("last_error", models.CharField(blank=True, default="", max_length=255)),
                (
                    "asset_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pod_drive_hd_sources",
                        to="uploads.assetversion",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pod_drive_hd_sources",
                        to="customers.customer",
                    ),
                ),
                (
                    "selected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_pod_drive_hd_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["customer", "status", "created_at"],
                        name="pod_hd_customer_status_idx",
                    ),
                    models.Index(
                        fields=["customer", "drive_file_id"],
                        name="pod_hd_customer_file_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer", "drive_file_id", "drive_version"),
                        name="pod_drive_hd_source_customer_file_version_uniq",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="podrecipeslot",
            name="source_drive_hd",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipe_slots",
                to="pod.poddrivehdsource",
            ),
        ),
    ]
