# Generated by Django 5.1.15 on 2026-04-02 06:47

import apps.shipping.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('sendcloud_shipment_id', models.CharField(blank=True, max_length=255)),
                ('sendcloud_parcel_id', models.CharField(blank=True, max_length=255)),
                ('sendcloud_status_code', models.CharField(blank=True, max_length=64)),
                ('sendcloud_status_message', models.CharField(blank=True, max_length=255)),
                ('shipping_option_code', models.CharField(max_length=128)),
                ('contract_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=255)),
                ('tracking_url', models.CharField(blank=True, max_length=2048)),
                ('label_file', models.FileField(blank=True, max_length=500, upload_to=apps.shipping.models.shipment_label_path)),
                ('label_filename', models.CharField(blank=True, max_length=255)),
                ('label_mime_type', models.CharField(blank=True, max_length=128)),
                ('label_retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('last_api_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(default='staff_api', max_length=32)),
                ('request_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'permissions': [('create_shipment', 'Can create shipment')],
                'indexes': [models.Index(fields=['status', 'updated_at'], name='shipping_sh_status_755ce0_idx'), models.Index(fields=['sendcloud_parcel_id'], name='shipping_sh_sendclo_26eb4a_idx'), models.Index(fields=['order', 'status'], name='shipping_sh_order_i_242975_idx')],
            },
        ),
    ]
