# Generated by Django 5.1.15 on 2026-07-26 09:57

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


def seed_shipping_methods(apps, schema_editor):
    ShippingMethod = apps.get_model("shipping", "ShippingMethod")
    defaults = (
        {
            "code": "pickup",
            "name": "Retrait atelier",
            "description": "Retrait sur place — aucun frais d’expédition.",
            "base_price": Decimal("0.00"),
            "is_pickup": True,
            "eta_label": "Dès disponibilité atelier",
            "display_order": 10,
        },
        {
            "code": "standard",
            "name": "Livraison standard",
            "description": "Expédition transporteur en délai standard.",
            "base_price": Decimal("8.00"),
            "is_pickup": False,
            "eta_label": "48–72 h après expédition",
            "display_order": 20,
        },
        {
            "code": "express",
            "name": "Livraison express",
            "description": "Expédition prioritaire.",
            "base_price": Decimal("18.00"),
            "is_pickup": False,
            "eta_label": "24 h après expédition",
            "display_order": 30,
        },
    )
    for payload in defaults:
        ShippingMethod.objects.get_or_create(
            code=payload["code"],
            defaults={
                **payload,
                "currency": "EUR",
                "is_active": True,
            },
        )


def unseed_shipping_methods(apps, schema_editor):
    ShippingMethod = apps.get_model("shipping", "ShippingMethod")
    ShippingMethod.objects.filter(code__in=["pickup", "standard", "express"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0003_shipment_sendcloud_order_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Frais d’expédition HT (EUR). Forcé à 0 si retrait atelier.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "is_pickup",
                    models.BooleanField(default=False, help_text="Retrait atelier : aucun frais d’expédition."),
                ),
                (
                    "eta_label",
                    models.CharField(
                        blank=True,
                        help_text="Indication délai affichée au client (ex. 48–72 h).",
                        max_length=128,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.AddIndex(
            model_name="shippingmethod",
            index=models.Index(fields=["is_active", "display_order"], name="shipping_sh_is_acti_7cf301_idx"),
        ),
        migrations.AddIndex(
            model_name="shippingmethod",
            index=models.Index(fields=["is_pickup", "is_active"], name="shipping_sh_is_pick_e4f587_idx"),
        ),
        migrations.RunPython(seed_shipping_methods, unseed_shipping_methods),
    ]
