# Generated by Django 5.2.17 on 2026-08-11 11:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0015_shipping_methods_and_order_vat"),
        ("shipping", "0004_shipping_methods_and_order_vat"),
    ]

    operations = [
        migrations.CreateModel(
            name="SendcloudWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("event_key", models.CharField(max_length=80)),
                ("provider_event_id", models.CharField(blank=True, max_length=255)),
                ("payload_hash", models.CharField(max_length=64)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sendcloud_webhook_events",
                        to="customers.customer",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="shipping.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["customer", "created_at"],
                        name="ship_sc_cust_created_idx",
                    ),
                    models.Index(
                        fields=["shipment", "created_at"],
                        name="ship_sc_ship_created_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer", "event_key"),
                        name="shipping_sc_event_key_uniq",
                    ),
                ],
            },
        ),
    ]
