# Generated by Django 5.0.6 on 2026-04-04 13:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_primary_contact_customermembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensuelle'), ('bi_monthly', 'Bi-mensuelle')], default='monthly', max_length=16)),
                ('credit_limit_eur', models.DecimalField(blank=True, decimal_places=2, help_text="Plafond d'encours optionnel (EUR).", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('enforce_credit_block', models.BooleanField(default=False, help_text='Si vrai, dépassement de plafond marque la commande en blocage encours.')),
                ('price_per_sqm_eur', models.DecimalField(blank=True, decimal_places=2, help_text="Prix au m² pour DTF : si vide, le catalogue (service DTF au mètre) s'applique.", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='customers.customer')),
            ],
            options={
                'ordering': ('customer__name',),
            },
        ),
    ]
