# Generated by Django 5.1.15 on 2026-04-24 05:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_preferred_settlement_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbillingprofile',
            name='price_per_sqm_eur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix au m² DTF pour ce client : si renseigné, il remplace le prix du service catalogue pour le calcul de tarification différée.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
