# Generated by Django 5.1.15 on 2026-07-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customerbillingprofile_price_per_sqm_eur'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='b2b_order_projects_enabled',
            field=models.BooleanField(default=False, help_text='Activation IDS explicite du parcours projet avant commande.', verbose_name='Projets de commande B2B activés'),
        ),
    ]
