# Generated by Django 5.1.15 on 2026-07-14 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_b2b_order_projects_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='siren',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='customermembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Propriétaire'), ('admin', 'Administrateur'), ('member', 'Collaborateur'), ('readonly', 'Lecture seule')], default='member', max_length=16),
        ),
        migrations.CreateModel(
            name='CustomerInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Propriétaire'), ('admin', 'Administrateur'), ('member', 'Collaborateur'), ('readonly', 'Lecture seule')], default='member', max_length=16)),
                ('kind', models.CharField(choices=[('owner_activation', 'Activation du propriétaire'), ('collaborator', "Invitation d'un collaborateur")], default='collaborator', max_length=24)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('revoked', 'Révoquée'), ('expired', 'Expirée')], db_index=True, default='pending', max_length=16)),
                ('token_version', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_invitations_accepted', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='customers.customer')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['customer', 'status', 'created_at'], name='customers_c_custome_660677_idx'), models.Index(fields=['email', 'status'], name='customers_c_email_ab3b52_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('customer', 'email'), name='uniq_pending_customer_invitation_email')],
            },
        ),
    ]
