# Generated by Django 5.1.15 on 2026-07-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_customer_default_billing_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='preferred_settlement_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe (carte)'), ('wire_transfer', 'Virement bancaire')], default='wire_transfer', help_text='Préférence affichée côté Atelier. Pour une commande en paiement immédiat, le client choisit parmi les moyens installés (PayPal, carte / Stripe).', max_length=24, verbose_name='Mode de règlement préféré'),
        ),
    ]
