# Generated by Django 5.1.15 on 2026-07-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_sync_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='default_billing_mode',
            field=models.CharField(choices=[('deferred', 'Encours / facturation différée'), ('immediate', 'Paiement comptant (carte bancaire)')], default='deferred', help_text='Mode de règlement du compte B2B : encours (facturation différée) ou comptant carte bancaire. En comptant, l’encours n’est plus proposé à la transmission. En encours, le client peut encore passer une commande en comptant CB.', max_length=16, verbose_name='Mode de règlement par défaut'),
        ),
    ]
