# Generated by Django 5.1.15 on 2026-07-26 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_default_billing_mode_lock_help'),
        ('shipping', '0004_shipping_methods_and_order_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_shipping_method',
            field=models.ForeignKey(blank=True, help_text='Préselection client à la transmission (retrait / standard / express). Si vide : dérivée du mode d’acheminement par défaut.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_customers', to='shipping.shippingmethod', verbose_name='Option de livraison préférée'),
        ),
    ]
