# Generated by Django 5.2.17 on 2026-08-13 07:40

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_customer_volume_discount_tiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCustomerVolumeDiscountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('minimum_monthly_linear_m', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Seuil mensuel (m linéaires)')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Remise (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Palier actif')),
            ],
            options={
                'verbose_name': 'Palier de remise par défaut',
                'verbose_name_plural': 'Paliers de remise par défaut',
                'ordering': ('minimum_monthly_linear_m', 'created_at'),
                'indexes': [models.Index(fields=['is_active', 'minimum_monthly_linear_m'], name='default_vol_tier_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('minimum_monthly_linear_m',), name='uniq_default_volume_discount_threshold'), models.CheckConstraint(condition=models.Q(('minimum_monthly_linear_m__gt', 0)), name='default_volume_discount_threshold_positive'), models.CheckConstraint(condition=models.Q(('discount_percent__gt', 0), ('discount_percent__lte', Decimal('100.00'))), name='default_volume_discount_percent_valid')],
            },
        ),
    ]
