# Generated by Django 5.2.17 on 2026-08-19 11:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_defaultcustomervolumediscounttier'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeDiscountDashboardCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('start_immediate', models.CharField(blank=True, max_length=400, verbose_name='Compteur à zéro (comptant)')),
                ('start_deferred', models.CharField(blank=True, max_length=400, verbose_name='Compteur à zéro (encours)')),
                ('warm_immediate', models.CharField(blank=True, max_length=400, verbose_name='En route (comptant)')),
                ('warm_deferred', models.CharField(blank=True, max_length=400, verbose_name='En route (encours)')),
                ('hold_immediate', models.CharField(blank=True, max_length=400, verbose_name='Palier en poche (comptant)')),
                ('hold_deferred', models.CharField(blank=True, max_length=400, verbose_name='Palier en poche (encours)')),
                ('hot_immediate', models.CharField(blank=True, max_length=400, verbose_name='Tout proche (comptant)')),
                ('hot_deferred', models.CharField(blank=True, max_length=400, verbose_name='Tout proche (encours)')),
                ('max_immediate', models.CharField(blank=True, max_length=400, verbose_name='Palier max (comptant)')),
                ('max_deferred', models.CharField(blank=True, max_length=400, verbose_name='Palier max (encours)')),
            ],
            options={
                'verbose_name': 'Messages dashboard remise volume',
                'verbose_name_plural': 'Messages dashboard remise volume',
            },
        ),
    ]
