from django.urls import path

from .views_access_management import (
    ClientTeamInvitationRevokeView,
    ClientTeamInviteView,
    ClientTeamMemberDeactivateView,
    ClientTeamMemberRoleView,
    ClientTeamView,
    CustomerInvitationAcceptView,
    CustomerInvitationCompleteView,
    StaffAccessRequestApproveView,
    StaffAccessRequestDetailView,
    StaffAccessRequestListView,
    StaffAccessRequestRejectView,
    StaffInvitationAcceptView,
    StaffInvitationCompleteView,
)
from .views_auth import (
    PortalLoginView,
    PortalLogoutView,
    PortalPasswordResetCompleteView,
    PortalPasswordResetConfirmView,
    PortalPasswordResetDoneView,
    PortalPasswordResetRequestView,
)
from .views_b2b_order_projects import (
    ClientOrderProjectAutosaveView,
    ClientOrderProjectCancelView,
    ClientOrderProjectCreateView,
    ClientOrderProjectDetailView,
    ClientOrderProjectItemActionView,
    ClientOrderProjectItemAssetDownloadView,
    ClientOrderProjectItemAssetPreviewView,
    ClientOrderProjectItemAssetView,
    ClientOrderProjectItemCreateView,
    ClientOrderProjectItemSemiTransparencyOverlayView,
    ClientOrderProjectItemThinZoneOverlayView,
    ClientOrderProjectListView,
    ClientOrderProjectSubmitView,
    StaffOrderProjectDetailView,
    StaffOrderProjectItemAssetDownloadView,
    StaffOrderProjectListView,
)
from .views_checkout import (
    ClientCheckoutSubmitView,
    ClientCheckoutSummaryPartialView,
    ClientCheckoutUploadPartialView,
    ClientCheckoutView,
)
from .views_client import (
    ClientDashboardView,
    ClientOrderDetailView,
    ClientOrderListView,
    ClientOrderPanelBillingView,
    ClientOrderPanelInspectionView,
    ClientOrderPanelProductionView,
    ClientOrderPanelShippingView,
    ClientOrderPanelUploadsView,
    ClientOrderReorderView,
    ClientOrderUploadDownloadView,
    ClientOrderUploadPreviewView,
)
from .views_gang_sheets import (
    ClientGangSheetAddItemView,
    ClientGangSheetAssetGalleryView,
    ClientGangSheetAssetPreviewView,
    ClientGangSheetAssetUploadView,
    ClientGangSheetBatchDeleteItemsView,
    ClientGangSheetCreateOrderProjectView,
    ClientGangSheetDeleteView,
    ClientGangSheetEditorView,
    ClientGangSheetItemActionView,
    ClientGangSheetLayoutView,
    ClientGangSheetListCreateView,
    ClientGangSheetPreviewDownloadView,
    ClientGangSheetSourceAssetRemoveView,
    ClientGangSheetStateView,
    ClientGangSheetWorkflowActionView,
    StaffGangSheetFinalDownloadView,
    StaffGangSheetSettingsView,
)
from .views_payments import (
    ClientOrderPaymentCaptureView,
    ClientOrderPaymentInitiateView,
    ClientOrderPaymentReturnView,
)
from .views_profile import (
    ClientCompanyProfileView,
    PortalProfileIdentityView,
    PortalProfileView,
)
from .views_staff import (
    StaffOrderDeleteView,
    StaffOrderDetailView,
    StaffOrderListView,
    StaffOrderPriceView,
)
from .views_staff_billing import StaffInvoiceMarkPaidView, StaffOrderPanelBillingView
from .views_staff_billing_statements import (
    StaffCustomerBillingStatementCreateView,
    StaffCustomerBillingStatementExportView,
)
from .views_staff_branding import StaffBrandSettingsView
from .views_staff_catalog import StaffDefaultCatalogPricingSettingsView
from .views_staff_processing_time import StaffProcessingTimeSettingsView
from .views_staff_customers import (
    StaffCustomerAccountUpdateView,
    StaffCustomerDetailView,
    StaffCustomerListView,
    StaffCustomerPricingUpdateView,
    StaffCustomerProcessingTimeUpdateView,
    StaffCustomerVolumeDiscountTierCreateView,
    StaffCustomerVolumeDiscountTierUpdateView,
    StaffDefaultVolumeDiscountSettingsView,
    StaffDefaultVolumeDiscountTierCreateView,
    StaffDefaultVolumeDiscountTierUpdateView,
    StaffVolumeDiscountDashboardCopyUpdateView,
)
from .views_staff_dashboard import StaffDashboardView
from .views_staff_documents import StaffManufacturingOrderBatchPdfView
from .views_staff_machine_jobs import (
    StaffOrderMachineAssignmentView,
    StaffOrderPrintConfirmView,
)
from .views_staff_machines import (
    StaffMachineCreateView,
    StaffMachineFleetView,
    StaffMachineUpdateView,
)
from .views_staff_notifications import (
    StaffEmailTemplateEditView,
    StaffEmailTemplateListView,
)
from .views_staff_operations import (
    StaffAtelierOperationMachineAssignView,
    StaffAtelierOperationMeterageView,
    StaffAtelierOperationPrintConfirmView,
    StaffAtelierOperationShipmentCreateView,
    StaffAtelierOperationShipmentSyncView,
    StaffAtelierOperationsView,
    StaffAtelierOperationTransitionView,
    StaffAtelierOperationUploadReviewView,
)
from .views_staff_pod import (
    StaffPodBlankDetailView,
    StaffPodBlankListView,
    StaffPodHubView,
    StaffPodLocationDetailView,
    StaffPodTechniqueListView,
    StaffPodWarehouseView,
)
from .views_staff_pod_catalog import (
    StaffPodCatalogListView,
    StaffPodCatalogProductView,
    StaffPodVariantConfigDrawerView,
)
from .views_staff_pod_ops import (
    StaffPodPoseDtfView,
    StaffPodStockView,
    StaffPodUnitDocumentView,
)
from .views_staff_pod_rip import StaffPodRipLotDetailView, StaffPodRipLotListView
from .views_staff_pod_shopify import StaffPodShopifyStoresView
from .views_staff_production import StaffOrderPanelProductionView
from .views_staff_reviews import (
    StaffOrderPanelInspectionView,
    StaffOrderUploadPreviewView,
    StaffOrderUploadReviewView,
)
from .views_staff_scan import StaffOrderPanelScanView
from .views_staff_team import (
    StaffTeamInvitationRevokeView,
    StaffTeamInviteView,
    StaffTeamMemberDeactivateView,
    StaffTeamMemberRoleView,
    StaffTeamView,
)
from .views_staff_shipping import (
    StaffOrderPanelShippingSyncView,
    StaffOrderPanelShippingView,
    StaffOrderShipmentLabelDownloadView,
)
from .views_staff_uploads import (
    StaffOrderPanelDriveSyncView,
    StaffOrderPanelUploadsView,
)

app_name = "portal"

urlpatterns = [
    path("login/", PortalLoginView.as_view(), name="login"),
    path("logout/", PortalLogoutView.as_view(), name="logout"),
    path(
        "mot-de-passe-oublie/",
        PortalPasswordResetRequestView.as_view(),
        name="password-reset",
    ),
    path(
        "mot-de-passe-oublie/envoye/",
        PortalPasswordResetDoneView.as_view(),
        name="password-reset-done",
    ),
    path(
        "mot-de-passe-oublie/termine/",
        PortalPasswordResetCompleteView.as_view(),
        name="password-reset-complete",
    ),
    path(
        "mot-de-passe-oublie/<uidb64>/<token>/",
        PortalPasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
    path("account/profile/", PortalProfileView.as_view(), name="profile"),
    path(
        "account/profile/identity/",
        PortalProfileIdentityView.as_view(),
        name="profile-identity",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/company/",
        ClientCompanyProfileView.as_view(),
        name="client-company-profile",
    ),
    path(
        "acces/invitation/<str:token>/",
        CustomerInvitationAcceptView.as_view(),
        name="customer-invitation-accept",
    ),
    path(
        "acces/activation-terminee/",
        CustomerInvitationCompleteView.as_view(),
        name="customer-invitation-complete",
    ),
    path(
        "acces/invitation-atelier/<str:token>/",
        StaffInvitationAcceptView.as_view(),
        name="staff-invitation-accept",
    ),
    path(
        "acces/activation-atelier-terminee/",
        StaffInvitationCompleteView.as_view(),
        name="staff-invitation-complete",
    ),
    path("client/", ClientDashboardView.as_view(), name="client-dashboard"),
    path(
        "client/customers/<uuid:customer_public_id>/team/",
        ClientTeamView.as_view(),
        name="client-team",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/team/invite/",
        ClientTeamInviteView.as_view(),
        name="client-team-invite",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/team/invitations/<uuid:invitation_public_id>/revoke/",
        ClientTeamInvitationRevokeView.as_view(),
        name="client-team-invitation-revoke",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/team/members/<uuid:membership_public_id>/role/",
        ClientTeamMemberRoleView.as_view(),
        name="client-team-member-role",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/team/members/<uuid:membership_public_id>/deactivate/",
        ClientTeamMemberDeactivateView.as_view(),
        name="client-team-member-deactivate",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/order-projects/",
        ClientOrderProjectListView.as_view(),
        name="client-order-project-list",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/order-projects/new/",
        ClientOrderProjectCreateView.as_view(),
        name="client-order-project-create",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/order-projects/<uuid:project_public_id>/",
        ClientOrderProjectDetailView.as_view(),
        name="client-order-project-detail",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/order-projects/<uuid:project_public_id>/autosave/",
        ClientOrderProjectAutosaveView.as_view(),
        name="client-order-project-autosave",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/order-projects/<uuid:project_public_id>/items/",
        ClientOrderProjectItemCreateView.as_view(),
        name="client-order-project-item-create",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/order-projects/<uuid:project_public_id>/items/<uuid:item_public_id>/<str:action>/",
        ClientOrderProjectItemActionView.as_view(),
        name="client-order-project-item-action",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/order-projects/<uuid:project_public_id>/items/<uuid:item_public_id>/asset/download/",
        ClientOrderProjectItemAssetDownloadView.as_view(),
        name="client-order-project-item-asset-download",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/order-projects/<uuid:project_public_id>/items/<uuid:item_public_id>/asset/preview/",
        ClientOrderProjectItemAssetPreviewView.as_view(),
        name="client-order-project-item-asset-preview",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/order-projects/<uuid:project_public_id>/items/<uuid:item_public_id>/asset/thin-zones/",
        ClientOrderProjectItemThinZoneOverlayView.as_view(),
        name="client-order-project-item-thin-zone-overlay",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/order-projects/<uuid:project_public_id>/items/<uuid:item_public_id>/asset/semi-transparency/",
        ClientOrderProjectItemSemiTransparencyOverlayView.as_view(),
        name="client-order-project-item-semi-transparency-overlay",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/order-projects/<uuid:project_public_id>/items/<uuid:item_public_id>/asset/<str:action>/",
        ClientOrderProjectItemAssetView.as_view(),
        name="client-order-project-item-asset",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/order-projects/<uuid:project_public_id>/submit/",
        ClientOrderProjectSubmitView.as_view(),
        name="client-order-project-submit",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/order-projects/<uuid:project_public_id>/cancel/",
        ClientOrderProjectCancelView.as_view(),
        name="client-order-project-cancel",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/gang-sheets/",
        ClientGangSheetListCreateView.as_view(),
        name="client-gang-sheet-list-create",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/gang-sheets/<uuid:sheet_public_id>/",
        ClientGangSheetEditorView.as_view(),
        name="client-gang-sheet-editor",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/gang-sheets/<uuid:sheet_public_id>/create-order/",
        ClientGangSheetCreateOrderProjectView.as_view(),
        name="client-gang-sheet-create-order-project",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/gang-sheets/<uuid:sheet_public_id>/delete/",
        ClientGangSheetDeleteView.as_view(),
        name="client-gang-sheet-delete",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/gang-sheets/<uuid:sheet_public_id>/state/",
        ClientGangSheetStateView.as_view(),
        name="client-gang-sheet-state",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/gang-sheets/<uuid:sheet_public_id>/layout/",
        ClientGangSheetLayoutView.as_view(),
        name="client-gang-sheet-layout",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/gang-sheets/<uuid:sheet_public_id>/items/add/",
        ClientGangSheetAddItemView.as_view(),
        name="client-gang-sheet-item-add",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/gang-sheets/<uuid:sheet_public_id>/items/delete-batch/",
        ClientGangSheetBatchDeleteItemsView.as_view(),
        name="client-gang-sheet-items-delete-batch",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/gang-sheets/<uuid:sheet_public_id>/items/<uuid:item_public_id>/<str:action>/",
        ClientGangSheetItemActionView.as_view(),
        name="client-gang-sheet-item-action",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/gang-sheets/<uuid:sheet_public_id>/actions/<str:action>/",
        ClientGangSheetWorkflowActionView.as_view(),
        name="client-gang-sheet-workflow-action",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/gang-sheets/<uuid:sheet_public_id>/assets/<uuid:asset_version_public_id>/preview/",
        ClientGangSheetAssetPreviewView.as_view(),
        name="client-gang-sheet-asset-preview",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/gang-sheets/<uuid:sheet_public_id>/assets/gallery/",
        ClientGangSheetAssetGalleryView.as_view(),
        name="client-gang-sheet-asset-gallery",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/gang-sheets/<uuid:sheet_public_id>/assets/upload/",
        ClientGangSheetAssetUploadView.as_view(),
        name="client-gang-sheet-asset-upload",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/gang-sheets/<uuid:sheet_public_id>/assets/<uuid:source_asset_public_id>/remove/",
        ClientGangSheetSourceAssetRemoveView.as_view(),
        name="client-gang-sheet-source-asset-remove",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/gang-sheets/<uuid:sheet_public_id>/preview/download/",
        ClientGangSheetPreviewDownloadView.as_view(),
        name="client-gang-sheet-preview-download",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/orders/",
        ClientOrderListView.as_view(),
        name="client-order-list",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/orders/<uuid:order_public_id>/",
        ClientOrderDetailView.as_view(),
        name="client-order-detail",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/orders/<uuid:order_public_id>/panels/uploads/",
        ClientOrderPanelUploadsView.as_view(),
        name="client-order-panel-uploads",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/orders/<uuid:order_public_id>/panels/inspection/",
        ClientOrderPanelInspectionView.as_view(),
        name="client-order-panel-inspection",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/orders/<uuid:order_public_id>/panels/production/",
        ClientOrderPanelProductionView.as_view(),
        name="client-order-panel-production",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/orders/<uuid:order_public_id>/panels/shipping/",
        ClientOrderPanelShippingView.as_view(),
        name="client-order-panel-shipping",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/orders/<uuid:order_public_id>/panels/billing/",
        ClientOrderPanelBillingView.as_view(),
        name="client-order-panel-billing",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/orders/<uuid:order_public_id>/payments/initiate/",
        ClientOrderPaymentInitiateView.as_view(),
        name="client-order-payment-initiate",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/orders/<uuid:order_public_id>/payments/return/",
        ClientOrderPaymentReturnView.as_view(),
        name="client-order-payment-return",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/orders/<uuid:order_public_id>/payments/capture/",
        ClientOrderPaymentCaptureView.as_view(),
        name="client-order-payment-capture",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/orders/<uuid:order_public_id>/uploads/<uuid:upload_public_id>/preview/",
        ClientOrderUploadPreviewView.as_view(),
        name="client-order-upload-preview",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/orders/<uuid:order_public_id>/uploads/<uuid:upload_public_id>/download/",
        ClientOrderUploadDownloadView.as_view(),
        name="client-order-upload-download",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/orders/<uuid:order_public_id>/reorder/",
        ClientOrderReorderView.as_view(),
        name="client-order-reorder",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/checkout/",
        ClientCheckoutView.as_view(),
        name="client-checkout",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/checkout/upload/",
        ClientCheckoutUploadPartialView.as_view(),
        name="client-checkout-upload",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/checkout/summary/",
        ClientCheckoutSummaryPartialView.as_view(),
        name="client-checkout-summary",
    ),
    path(
        "client/customers/<uuid:customer_public_id>/checkout/submit/",
        ClientCheckoutSubmitView.as_view(),
        name="client-checkout-submit",
    ),
    path("staff/", StaffDashboardView.as_view(), name="staff-dashboard"),
    path(
        "staff/atelier/pilotage/",
        StaffAtelierOperationsView.as_view(),
        name="staff-atelier-operations",
    ),
    path(
        "staff/atelier/pilotage/<uuid:order_public_id>/transition/",
        StaffAtelierOperationTransitionView.as_view(),
        name="staff-atelier-operation-transition",
    ),
    path(
        "staff/atelier/pilotage/<uuid:order_public_id>/uploads/<uuid:upload_public_id>/review/",
        StaffAtelierOperationUploadReviewView.as_view(),
        name="staff-atelier-operation-upload-review",
    ),
    path(
        "staff/atelier/pilotage/<uuid:order_public_id>/machine/",
        StaffAtelierOperationMachineAssignView.as_view(),
        name="staff-atelier-operation-machine-assign",
    ),
    path(
        "staff/atelier/pilotage/<uuid:order_public_id>/print/",
        StaffAtelierOperationPrintConfirmView.as_view(),
        name="staff-atelier-operation-print-confirm",
    ),
    path(
        "staff/atelier/pilotage/<uuid:order_public_id>/meterage/",
        StaffAtelierOperationMeterageView.as_view(),
        name="staff-atelier-operation-meterage",
    ),
    path(
        "staff/atelier/pilotage/<uuid:order_public_id>/shipment/create/",
        StaffAtelierOperationShipmentCreateView.as_view(),
        name="staff-atelier-operation-shipment-create",
    ),
    path(
        "staff/atelier/pilotage/<uuid:order_public_id>/shipment/sync/",
        StaffAtelierOperationShipmentSyncView.as_view(),
        name="staff-atelier-operation-shipment-sync",
    ),
    path("staff/atelier/pod/", StaffPodHubView.as_view(), name="staff-pod-hub"),
    path(
        "staff/atelier/pod/techniques/",
        StaffPodTechniqueListView.as_view(),
        name="staff-pod-techniques",
    ),
    path(
        "staff/atelier/pod/blanks/",
        StaffPodBlankListView.as_view(),
        name="staff-pod-blanks",
    ),
    path(
        "staff/atelier/pod/blanks/<uuid:blank_public_id>/",
        StaffPodBlankDetailView.as_view(),
        name="staff-pod-blank-detail",
    ),
    path(
        "staff/atelier/pod/entrepot/",
        StaffPodWarehouseView.as_view(),
        name="staff-pod-warehouse",
    ),
    path(
        "staff/atelier/pod/entrepot/emplacements/<uuid:location_public_id>/",
        StaffPodLocationDetailView.as_view(),
        name="staff-pod-location-detail",
    ),
    path(
        "staff/atelier/pod/catalogue/",
        StaffPodCatalogListView.as_view(),
        name="staff-pod-catalog",
    ),
    path(
        "staff/atelier/pod/catalogue/<uuid:product_public_id>/",
        StaffPodCatalogProductView.as_view(),
        name="staff-pod-catalog-product",
    ),
    path(
        "staff/atelier/pod/catalogue/variantes/<uuid:variant_public_id>/config/",
        StaffPodVariantConfigDrawerView.as_view(),
        name="staff-pod-variant-config",
    ),
    path(
        "staff/atelier/pod/boutiques/",
        StaffPodShopifyStoresView.as_view(),
        name="staff-pod-shops",
    ),
    path(
        "staff/atelier/pod/lots/",
        StaffPodRipLotListView.as_view(),
        name="staff-pod-rip-lots",
    ),
    path(
        "staff/atelier/pod/lots/<uuid:lot_public_id>/",
        StaffPodRipLotDetailView.as_view(),
        name="staff-pod-rip-lot-detail",
    ),
    path(
        "staff/atelier/pod/pose/dtf/",
        StaffPodPoseDtfView.as_view(),
        name="staff-pod-pose-dtf",
    ),
    path(
        "staff/atelier/pod/stocks/",
        StaffPodStockView.as_view(),
        name="staff-pod-stock",
    ),
    path(
        "staff/atelier/pod/pieces/<uuid:unit_public_id>/<str:document_kind>/",
        StaffPodUnitDocumentView.as_view(),
        name="staff-pod-unit-document",
    ),
    path(
        "staff/machines/",
        StaffMachineFleetView.as_view(),
        name="staff-machine-fleet",
    ),
    path(
        "staff/machines/create/",
        StaffMachineCreateView.as_view(),
        name="staff-machine-create",
    ),
    path(
        "staff/machines/<uuid:machine_public_id>/update/",
        StaffMachineUpdateView.as_view(),
        name="staff-machine-update",
    ),
    path("staff/team/", StaffTeamView.as_view(), name="staff-team"),
    path("staff/team/invite/", StaffTeamInviteView.as_view(), name="staff-team-invite"),
    path(
        "staff/team/invitations/<uuid:invitation_public_id>/revoke/",
        StaffTeamInvitationRevokeView.as_view(),
        name="staff-team-invitation-revoke",
    ),
    path(
        "staff/team/members/<uuid:membership_public_id>/role/",
        StaffTeamMemberRoleView.as_view(),
        name="staff-team-member-role",
    ),
    path(
        "staff/team/members/<uuid:membership_public_id>/deactivate/",
        StaffTeamMemberDeactivateView.as_view(),
        name="staff-team-member-deactivate",
    ),
    path(
        "staff/access-requests/",
        StaffAccessRequestListView.as_view(),
        name="staff-access-request-list",
    ),
    path(
        "staff/customers/",
        StaffCustomerListView.as_view(),
        name="staff-customer-list",
    ),
    path(
        "staff/customers/<uuid:customer_public_id>/",
        StaffCustomerDetailView.as_view(),
        name="staff-customer-detail",
    ),
    path(
        "staff/customers/<uuid:customer_public_id>/account/",
        StaffCustomerAccountUpdateView.as_view(),
        name="staff-customer-account-update",
    ),
    path(
        "staff/customers/<uuid:customer_public_id>/pricing/",
        StaffCustomerPricingUpdateView.as_view(),
        name="staff-customer-pricing-update",
    ),
    path(
        "staff/customers/<uuid:customer_public_id>/processing-time/",
        StaffCustomerProcessingTimeUpdateView.as_view(),
        name="staff-customer-processing-time-update",
    ),
    path(
        "staff/customers/<uuid:customer_public_id>/pricing/volume-tiers/",
        StaffCustomerVolumeDiscountTierCreateView.as_view(),
        name="staff-customer-volume-discount-tier-create",
    ),
    path(
        "staff/customers/<uuid:customer_public_id>/pricing/volume-tiers/<uuid:tier_public_id>/",
        StaffCustomerVolumeDiscountTierUpdateView.as_view(),
        name="staff-customer-volume-discount-tier-update",
    ),
    path(
        "staff/customers/<uuid:customer_public_id>/billing-statements/",
        StaffCustomerBillingStatementCreateView.as_view(),
        name="staff-customer-billing-statement-create",
    ),
    path(
        "staff/customers/<uuid:customer_public_id>/billing-statements/<uuid:statement_public_id>/export.csv",
        StaffCustomerBillingStatementExportView.as_view(),
        name="staff-customer-billing-statement-export",
    ),
    path(
        "staff/access-requests/<uuid:profile_public_id>/",
        StaffAccessRequestDetailView.as_view(),
        name="staff-access-request-detail",
    ),
    path(
        "staff/access-requests/<uuid:profile_public_id>/approve/",
        StaffAccessRequestApproveView.as_view(),
        name="staff-access-request-approve",
    ),
    path(
        "staff/access-requests/<uuid:profile_public_id>/reject/",
        StaffAccessRequestRejectView.as_view(),
        name="staff-access-request-reject",
    ),
    path(
        "staff/settings/email-templates/",
        StaffEmailTemplateListView.as_view(),
        name="staff-email-template-list",
    ),
    path(
        "staff/settings/branding/",
        StaffBrandSettingsView.as_view(),
        name="staff-brand-settings",
    ),
    path(
        "staff/settings/volume-discounts/",
        StaffDefaultVolumeDiscountSettingsView.as_view(),
        name="staff-default-volume-discount-settings",
    ),
    path(
        "staff/settings/catalog-pricing/",
        StaffDefaultCatalogPricingSettingsView.as_view(),
        name="staff-default-catalog-pricing-settings",
    ),
    path(
        "staff/settings/processing-time/",
        StaffProcessingTimeSettingsView.as_view(),
        name="staff-processing-time-settings",
    ),
    path(
        "staff/settings/volume-discounts/messages/",
        StaffVolumeDiscountDashboardCopyUpdateView.as_view(),
        name="staff-volume-discount-dashboard-copy",
    ),
    path(
        "staff/settings/volume-discounts/tiers/",
        StaffDefaultVolumeDiscountTierCreateView.as_view(),
        name="staff-default-volume-discount-tier-create",
    ),
    path(
        "staff/settings/volume-discounts/tiers/<uuid:tier_public_id>/",
        StaffDefaultVolumeDiscountTierUpdateView.as_view(),
        name="staff-default-volume-discount-tier-update",
    ),
    path(
        "staff/settings/gang-sheets/",
        StaffGangSheetSettingsView.as_view(),
        name="staff-gang-sheet-settings",
    ),
    path(
        "staff/gang-sheets/<uuid:sheet_public_id>/production/download/",
        StaffGangSheetFinalDownloadView.as_view(),
        name="staff-gang-sheet-final-download",
    ),
    path(
        "staff/settings/email-templates/<str:event>/<str:audience>/",
        StaffEmailTemplateEditView.as_view(),
        name="staff-email-template-edit",
    ),
    path(
        "staff/order-projects/",
        StaffOrderProjectListView.as_view(),
        name="staff-order-project-list",
    ),
    path(
        "staff/order-projects/<uuid:project_public_id>/",
        StaffOrderProjectDetailView.as_view(),
        name="staff-order-project-detail",
    ),
    path(
        "staff/order-projects/<uuid:project_public_id>/items/<uuid:item_public_id>/asset/download/",
        StaffOrderProjectItemAssetDownloadView.as_view(),
        name="staff-order-project-item-asset-download",
    ),
    path("staff/orders/", StaffOrderListView.as_view(), name="staff-order-list"),
    path(
        "staff/orders/manufacturing-orders/batch.pdf",
        StaffManufacturingOrderBatchPdfView.as_view(),
        name="staff-manufacturing-order-batch-pdf",
    ),
    path(
        "staff/orders/<uuid:order_public_id>/",
        StaffOrderDetailView.as_view(),
        name="staff-order-detail",
    ),
    path(
        "staff/orders/<uuid:order_public_id>/price/",
        StaffOrderPriceView.as_view(),
        name="staff-order-price",
    ),
    path(
        "staff/orders/<uuid:order_public_id>/delete/",
        StaffOrderDeleteView.as_view(),
        name="staff-order-delete",
    ),
    path(
        "staff/orders/<uuid:order_public_id>/panels/uploads/",
        StaffOrderPanelUploadsView.as_view(),
        name="staff-order-panel-uploads",
    ),
    path(
        "staff/orders/<uuid:order_public_id>/panels/inspection/",
        StaffOrderPanelInspectionView.as_view(),
        name="staff-order-panel-inspection",
    ),
    path(
        "staff/orders/<uuid:order_public_id>/uploads/<uuid:upload_public_id>/review/",
        StaffOrderUploadReviewView.as_view(),
        name="staff-order-upload-review",
    ),
    path(
        "staff/orders/<uuid:order_public_id>/uploads/<uuid:upload_public_id>/preview/",
        StaffOrderUploadPreviewView.as_view(),
        name="staff-order-upload-preview",
    ),
    path(
        "staff/orders/<uuid:order_public_id>/panels/drive-sync/",
        StaffOrderPanelDriveSyncView.as_view(),
        name="staff-order-panel-drive-sync",
    ),
    path(
        "staff/orders/<uuid:order_public_id>/panels/production/",
        StaffOrderPanelProductionView.as_view(),
        name="staff-order-panel-production",
    ),
    path(
        "staff/orders/<uuid:order_public_id>/machine-assignment/",
        StaffOrderMachineAssignmentView.as_view(),
        name="staff-order-machine-assignment",
    ),
    path(
        "staff/orders/<uuid:order_public_id>/print-confirmation/",
        StaffOrderPrintConfirmView.as_view(),
        name="staff-order-print-confirmation",
    ),
    path(
        "staff/orders/<uuid:order_public_id>/panels/shipping/sync/",
        StaffOrderPanelShippingSyncView.as_view(),
        name="staff-order-panel-shipping-sync",
    ),
    path(
        "staff/orders/<uuid:order_public_id>/panels/shipping/label/",
        StaffOrderShipmentLabelDownloadView.as_view(),
        name="staff-order-shipment-label-download",
    ),
    path(
        "staff/orders/<uuid:order_public_id>/panels/shipping/",
        StaffOrderPanelShippingView.as_view(),
        name="staff-order-panel-shipping",
    ),
    path(
        "staff/orders/<uuid:order_public_id>/panels/scan/",
        StaffOrderPanelScanView.as_view(),
        name="staff-order-panel-scan",
    ),
    path(
        "staff/orders/<uuid:order_public_id>/panels/billing/",
        StaffOrderPanelBillingView.as_view(),
        name="staff-order-panel-billing",
    ),
    path(
        "staff/orders/<uuid:order_public_id>/invoice/mark-paid/",
        StaffInvoiceMarkPaidView.as_view(),
        name="staff-order-invoice-mark-paid",
    ),
]
